const vocabularyData = [
  // --- UNIT 1 ---
  { id: 1, unit: "Unit 1", part: "Part 1", kanji: "男性", kana: "だんせい", romaji: "dansei", hanviet: "Nam Tính", meaning: "Nam giới", example: "理想の男性と結婚する。" },
  { id: 2, unit: "Unit 1", part: "Part 1", kanji: "女性", kana: "じょせい", romaji: "josei", hanviet: "Nữ Tính", meaning: "Nữ giới", example: "「あの女性はだれですか」" },
  { id: 3, unit: "Unit 1", part: "Part 1", kanji: "高齢", kana: "こうれい", romaji: "kourei", hanviet: "Cao Linh", meaning: "Cao tuổi", example: "祖母は高齢だが、まだとても元気だ。" },
  { id: 4, unit: "Unit 1", part: "Part 1", kanji: "年上", kana: "としうえ", romaji: "toshiue", hanviet: "Niên Thượng", meaning: "Lớn tuổi hơn", example: "彼女は私より三つ年上だ。" },
  { id: 5, unit: "Unit 1", part: "Part 1", kanji: "目上", kana: "めうえ", romaji: "meue", hanviet: "Mục Thượng", meaning: "Cấp trên, bề trên", example: "目上の人には敬語で話したほうがいい。" },
  { id: 6, unit: "Unit 1", part: "Part 1", kanji: "先輩", kana: "せんぱい", romaji: "senpai", hanviet: "Tiền Bối", meaning: "Tiền bối", example: "職場では彼のほうが先輩だ。" },
  { id: 7, unit: "Unit 1", part: "Part 1", kanji: "後輩", kana: "こうはい", romaji: "kouhai", hanviet: "Hậu Bối", meaning: "Hậu bối", example: "田中さんと私は同じ年だが、職場では彼のほうが先輩で、私は後輩だ。" },
  { id: 8, unit: "Unit 1", part: "Part 1", kanji: "上司", kana: "じょうし", romaji: "joushi", hanviet: "Thượng Ty", meaning: "Cấp trên, sếp", example: "上司に相談してから決定する。" },
  { id: 9, unit: "Unit 1", part: "Part 1", kanji: "相手", kana: "あいて", romaji: "aite", hanviet: "Tương Thủ", meaning: "Đối phương, đối thủ", example: "今度の試合の相手は強そうだ。" },
  { id: 10, unit: "Unit 1", part: "Part 1", kanji: "知り合い", kana: "しりあい", romaji: "shiriai", hanviet: "Tri Hợp", meaning: "Người quen", example: "知り合いに息子の就職を頼む。" },
  { id: 11, unit: "Unit 1", part: "Part 1", kanji: "友人", kana: "ゆうじん", romaji: "yuujin", hanviet: "Hữu Nhân", meaning: "Bạn bè", example: "「ええ、学生時代の友人です」" },
  { id: 12, unit: "Unit 1", part: "Part 1", kanji: "仲", kana: "なか", romaji: "naka", hanviet: "Trọng", meaning: "Mối quan hệ", example: "私は山本さんと仲がいい。" },
  { id: 13, unit: "Unit 1", part: "Part 1", kanji: "生年月日", kana: "せいねんがっぴ", romaji: "seinen gappi", hanviet: "Sinh Niên Nguyệt Nhật", meaning: "Ngày tháng năm sinh", example: "書類に生年月日を記入する。" },
  { id: 14, unit: "Unit 1", part: "Part 1", kanji: "誕生", kana: "たんじょう", romaji: "tanjou", hanviet: "Đản Sinh", meaning: "Sự ra đời, khai sinh", example: "新しい命の誕生を祝う。" },
  { id: 15, unit: "Unit 1", part: "Part 1", kanji: "年", kana: "とし", romaji: "toshi", hanviet: "Niên", meaning: "Năm, tuổi", example: "年の初めに1年の計画を立てる。" },
  { id: 16, unit: "Unit 1", part: "Part 1", kanji: "出身", kana: "しゅっしん", romaji: "shusshin", hanviet: "Xuất Thân", meaning: "Xuất thân, quê quán", example: "私は東京の出身です。" },
  { id: 17, unit: "Unit 1", part: "Part 1", kanji: "故郷", kana: "こきょう", romaji: "kokyou", hanviet: "Cố Hương", meaning: "Cố hương, quê nhà", example: "もう何年も故郷に帰っていない。" },
  { id: 18, unit: "Unit 1", part: "Part 1", kanji: "成長", kana: "せいちょう", romaji: "seichou", hanviet: "Thành Trưởng", meaning: "Trưởng thành, phát triển", example: "子どもの成長を喜ぶ。" },
  { id: 19, unit: "Unit 1", part: "Part 1", kanji: "成人", kana: "せいじん", romaji: "seijin", hanviet: "Thành Nhân", meaning: "Người trưởng thành", example: "日本では二十歳以上の人を成人という。" },
  { id: 20, unit: "Unit 1", part: "Part 1", kanji: "合格", kana: "ごうかく", romaji: "gougaku", hanviet: "Hợp Cách", meaning: "Đỗ, trúng tuyển", example: "入学試験に合格する。" },

  { id: 21, unit: "Unit 1", part: "Part 2", kanji: "進学", kana: "しんがく", romaji: "shingaku", hanviet: "Tiến Học", meaning: "Học lên cao hơn", example: "子どもの進学について考える。" },
  { id: 22, unit: "Unit 1", part: "Part 2", kanji: "退学", kana: "たいがく", romaji: "taigaku", hanviet: "Thoái Học", meaning: "Thôi học, bỏ học", example: "病気で大学を退学した。" },
  { id: 23, unit: "Unit 1", part: "Part 2", kanji: "就職", kana: "しゅうしょく", romaji: "shuushoku", hanviet: "Tựu Chức", meaning: "Có việc làm", example: "旅行会社に就職する。" },
  { id: 24, unit: "Unit 1", part: "Part 2", kanji: "退職", kana: "たいしょく", romaji: "taishoku", hanviet: "Thoái Chức", meaning: "Nghỉ việc, thôi việc", example: "長年勤めた会社を退職した。" },
  { id: 25, unit: "Unit 1", part: "Part 2", kanji: "失業", kana: "しつぎょう", romaji: "shitsugyou", hanviet: "Thất Nghiệp", meaning: "Thất nghiệp, mất việc", example: "会社が倒産して失業した。" },
  { id: 26, unit: "Unit 1", part: "Part 2", kanji: "残業", kana: "ざんぎょう", romaji: "zangyou", hanviet: "Tàn Nghiệp", meaning: "Làm thêm giờ", example: "残業が多くて疲れた。" },
  { id: 27, unit: "Unit 1", part: "Part 2", kanji: "生活", kana: "せいかつ", romaji: "seikatsu", hanviet: "Sinh Hoạt", meaning: "Cuộc sống, sinh hoạt", example: "健康的な生活を送る。" },
  { id: 28, unit: "Unit 1", part: "Part 2", kanji: "通勤", kana: "つうきん", romaji: "tsukin", hanviet: "Thông Cần", meaning: "Đi làm", example: "私は毎日1時間かけて通勤している。" },
  { id: 29, unit: "Unit 1", part: "Part 2", kanji: "学歴", kana: "がくれき", romaji: "gakureki", hanviet: "Học Lịch", meaning: "Học vấn, bằng cấp", example: "学歴が高くても、実力があるかはわからない。" },
  { id: 30, unit: "Unit 1", part: "Part 2", kanji: "給料", kana: "きゅうりょう", romaji: "kyuuryou", hanviet: "Cấp Liệu", meaning: "Tiền lương", example: "会社から給料をもらう。" },
  { id: 31, unit: "Unit 1", part: "Part 2", kanji: "面接", kana: "めんせつ", romaji: "mensetsu", hanviet: "Diện Tiếp", meaning: "Phỏng vấn", example: "きょう、会社の人との面接がある。" },
  { id: 32, unit: "Unit 1", part: "Part 2", kanji: "休憩", kana: "きゅうけい", romaji: "kyuukei", hanviet: "Hưu Khế", meaning: "Nghỉ giải lao", example: "「ではここで、10分間の休憩です」" },
  { id: 33, unit: "Unit 1", part: "Part 2", kanji: "観光", kana: "かんこう", romaji: "kankou", hanviet: "Quan Quang", meaning: "Tham quan, du lịch", example: "来日の目的は観光です。" },
  { id: 34, unit: "Unit 1", part: "Part 2", kanji: "帰国", kana: "きこく", romaji: "kikoku", hanviet: "Quy Quốc", meaning: "Về nước", example: "今度の正月には帰国するつもりだ。" },
  { id: 35, unit: "Unit 1", part: "Part 2", kanji: "帰省", kana: "きせい", romaji: "kisei", hanviet: "Quy Tỉnh", meaning: "Về quê thăm nhà", example: "お盆にはふるさとに帰省する日本人が多い。" },
  { id: 36, unit: "Unit 1", part: "Part 2", kanji: "帰宅", kana: "きたく", romaji: "kitaku", hanviet: "Quy Trạch", meaning: "Về nhà (hàng ngày)", example: "毎日忙しくて帰宅が遅い。" },
  { id: 37, unit: "Unit 1", part: "Part 2", kanji: "参加", kana: "さんか", romaji: "sanka", hanviet: "Tham Gia", meaning: "Tham gia", example: "ボランティア活動に参加する。" },
  { id: 38, unit: "Unit 1", part: "Part 2", kanji: "出席", kana: "しゅっせき", romaji: "shusseki", hanviet: "Xuất Tịch", meaning: "Có mặt, hiện diện", example: "ミーティングに出席する。" },
  { id: 39, unit: "Unit 1", part: "Part 2", kanji: "欠席", kana: "けっせき", romaji: "kesseki", hanviet: "Khiếm Tịch", meaning: "Vắng mặt, nghỉ học", example: "授業を欠席する。" },
  { id: 40, unit: "Unit 1", part: "Part 2", kanji: "遅刻", kana: "ちこく", romaji: "chikoku", hanviet: "Trì Khắc", meaning: "Đến muộn, trễ", example: "寝坊して授業に遅刻する。" },

  { id: 41, unit: "Unit 1", part: "Part 3", kanji: "化粧", kana: "けしょう", romaji: "keshou", hanviet: "Hóa Trang", meaning: "Trang điểm", example: "「あなたは毎日、お化粧に何分ぐらいかけていますか」" },
  { id: 42, unit: "Unit 1", part: "Part 3", kanji: "计算", kana: "けいさん", romaji: "keisan", hanviet: "Kế Toán", meaning: "Tính toán", example: "私は計算が苦手 da。" },
  { id: 43, unit: "Unit 1", part: "Part 3", kanji: "計画", kana: "けいかく", romaji: "keikaku", hanviet: "Kế Họa", meaning: "Kế hoạch", example: "来年の計画を立てる。" },
  { id: 44, unit: "Unit 1", part: "Part 3", kanji: "成功", kana: "せいこう", romaji: "seikou", hanviet: "Thành Công", meaning: "Thành công", example: "実験に成功する。" },
  { id: 45, unit: "Unit 1", part: "Part 3", kanji: "失敗", kana: "しっぱい", romaji: "shippai", hanviet: "Thất Bại", meaning: "Thất bại", example: "実験の失敗で、計画は中止になった。" },
  { id: 46, unit: "Unit 1", part: "Part 3", kanji: "準備", kana: "じゅんび", romaji: "junbi", hanviet: "Chuẩn Bị", meaning: "Chuẩn bị", example: "引っ越しの準備が終わった。" },
  { id: 47, unit: "Unit 1", part: "Part 3", kanji: "整理", kana: "せいり", romaji: "seiri", hanviet: "Chỉnh Lý", meaning: "Sắp xếp, thu dọn", example: "資料の整理。" },
  { id: 48, unit: "Unit 1", part: "Part 3", kanji: "注文", kana: "ちゅうもん", romaji: "chuumon", hanviet: "Chú Văn", meaning: "Đặt hàng, gọi món", example: "喫茶店でコーヒーを注文する。" },
  { id: 49, unit: "Unit 1", part: "Part 3", kanji: "貯金", kana: "ちょきん", romaji: "chokin", hanviet: "Trữ Kim", meaning: "Tiền tiết kiệm", example: "銀行にボーナスを貯金する。" },
  { id: 50, unit: "Unit 1", part: "Part 3", kanji: "徹夜", kana: "てつや", romaji: "tetsuya", hanviet: "Triệt Dạ", meaning: "Thức suốt đêm", example: "徹夜で勉強する。" },
  { id: 51, unit: "Unit 1", part: "Part 3", kanji: "引っ越し", kana: "ひっこし", romaji: "hikkoshi", hanviet: "Dẫn Việt", meaning: "Chuyển nhà", example: "引っ越しを手伝う。" },
  { id: 52, unit: "Unit 1", part: "Part 3", kanji: "身長", kana: "しんちょう", romaji: "shinchou", hanviet: "Thân Trường", meaning: "Chiều cao", example: "身長を測る。" },
  { id: 53, unit: "Unit 1", part: "Part 3", kanji: "体重", kana: "たいじゅう", romaji: "taijuu", hanviet: "Thể Trọng", meaning: "Cân nặng", example: "体重を量る。" },
  { id: 54, unit: "Unit 1", part: "Part 3", kanji: "けが", kana: "kega", romaji: "kega", hanviet: "", meaning: "Vết thương", example: "転んで足にけがをした。" },
  { id: 55, unit: "Unit 1", part: "Part 3", kanji: "会", kana: "かい", romaji: "kai", hanviet: "Hội", meaning: "Tiệc, buổi lễ", example: "忘年会を開く。" },
  { id: 56, unit: "Unit 1", part: "Part 3", kanji: "趣味", kana: "しゅみ", romaji: "shumi", hanviet: "Thú Vị", meaning: "Sở thích", example: "趣味は読書です。" },
  { id: 57, unit: "Unit 1", part: "Part 3", kanji: "興味", kana: "きょうみ", romaji: "kyoumi", hanviet: "Hưng Vị", meaning: "Hứng thú", example: "私は歴史に興味がある。" },
  { id: 58, unit: "Unit 1", part: "Part 3", kanji: "思い出", kana: "おもいで", romaji: "omoide", hanviet: "Tư Xuất", meaning: "Kỷ niệm", example: "子供のころの楽しい思い出。" },
  { id: 59, unit: "Unit 1", part: "Part 3", kanji: "冗談", kana: "じょうだん", romaji: "joudan", hanviet: "Nhũng Đàm", meaning: "Nói đùa", example: "冗談を言ったら、みんなが本気にした。" },
  { id: 60, unit: "Unit 1", part: "Part 3", kanji: "目的", kana: "もくてき", romaji: "mokuteki", hanviet: "Mục Đích", meaning: "Mục đích", example: "日本に来た目的は大学への入学だ。" },

  { id: 61, unit: "Unit 1", part: "Part 4", kanji: "約束", kana: "やくそく", romaji: "yakusoku", hanviet: "Ước Thúc", meaning: "Lời hứa, cuộc hẹn", example: "彼と結婚の約束をした。" },
  { id: 62, unit: "Unit 1", part: "Part 4", kanji: "おしゃべり", kana: "oshaberi", romaji: "oshaberi", hanviet: "", meaning: "Nói chuyện, tán gẫu", example: "授業 trung におしゃべりして、先生に怒られた。" },
  { id: 63, unit: "Unit 1", part: "Part 4", kanji: "遠慮", kana: "えんりょ", romaji: "enryo", hanviet: "Viễn Lự", meaning: "Ngại ngùng, giữ kẽ", example: "「遠慮しないで食べてください」" },
  { id: 64, unit: "Unit 1", part: "Part 4", kanji: "我慢", kana: "がまん", romaji: "gaman", hanviet: "Ngã Mạn", meaning: "Chịu đựng, nhẫn nại", example: "痛くてもがまんする。" },
  { id: 65, unit: "Unit 1", part: "Part 4", kanji: "迷惑", kana: "めいわく", romaji: "meiwaku", hanviet: "Mê Hoặc", meaning: "Làm phiền, quấy rầy", example: "人に迷惑をかけてはいけない。" },
  { id: 66, unit: "Unit 1", part: "Part 4", kanji: "希望", kana: "きぼう", romaji: "kibou", hanviet: "Hy Vọng", meaning: "Hy vọng, ý muốn", example: "最後まで希望を捨ててはいけない。" },
  { id: 67, unit: "Unit 1", part: "Part 4", kanji: "夢", kana: "ゆめ", romaji: "yume", hanviet: "Mộng", meaning: "Giấc mơ, ước mơ", example: "きのう、こわい夢を見た。" },
  { id: 68, unit: "Unit 1", part: "Part 4", kanji: "賛成", kana: "さんせい", romaji: "sansei", hanviet: "Tán Thành", meaning: "Tán thành, đồng ý", example: "「賛成の人は手を挙げてください」" },
  { id: 69, unit: "Unit 1", part: "Part 4", kanji: "反対", kana: "はんたい", romaji: "hantai", hanviet: "Phản Đối", meaning: "Phản đối, ngược lại", example: "彼の意見には反対だ。" },
  { id: 70, unit: "Unit 1", part: "Part 4", kanji: "想像", kana: "そうぞう", romaji: "souzou", hanviet: "Tưởng Tượng", meaning: "Tưởng tượng", example: "想像と現実は違う。" },
  { id: 71, unit: "Unit 1", part: "Part 4", kanji: "努力", kana: "どりょく", romaji: "doryoku", hanviet: "Nỗ Lực", meaning: "Nỗ lực, cố gắng", example: "一生懸命、努力をする。" },
  { id: 72, unit: "Unit 1", part: "Part 4", kanji: "太陽", kana: "たいよう", romaji: "taiyou", hanviet: "Thái Dương", meaning: "Mặt trời", example: "太陽が昇って、暖かくなった。" },
  { id: 73, unit: "Unit 1", part: "Part 4", kanji: "地球", kana: "ちきゅう", romaji: "chikyuu", hanviet: "Địa Cầu", meaning: "Trái đất", example: "地球の環境が悪化している。" },
  { id: 74, unit: "Unit 1", part: "Part 4", kanji: "温度", kana: "おんど", romaji: "ondo", hanviet: "Ôn Độ", meaning: "Nhiệt độ", example: "温度を測る。" },
  { id: 75, unit: "Unit 1", part: "Part 4", kanji: "湿度", kana: "しつど", romaji: "shitsudo", hanviet: "Thấp Độ", meaning: "Độ ẩm", example: "今年の夏は特に湿度が高い。" },
  { id: 76, unit: "Unit 1", part: "Part 4", kanji: "湿気", kana: "しっけ", romaji: "shikke", hanviet: "Thấp Khí", meaning: "Hơi ẩm", example: "日本の夏は湿気が多い。" },
  { id: 77, unit: "Unit 1", part: "Part 4", kanji: "梅雨", kana: "つゆ", romaji: "tsuyu", hanviet: "Mai Vũ", meaning: "Mùa mưa", example: "6月から7月は梅雨の時期だ。" },
  { id: 78, unit: "Unit 1", part: "Part 4", kanji: "かび", kana: "kabi", romaji: "kabi", hanviet: "", meaning: "Nấm mốc", example: "梅雨の時期はかびがはえやすい。" },
  { id: 79, unit: "Unit 1", part: "Part 4", kanji: "暖房", kana: "だんぼう", romaji: "danbou", hanviet: "Noãn Phòng", meaning: "Lò sưởi, hệ thống sưởi", example: "寒いので暖房をつける。" },
  { id: 80, unit: "Unit 1", part: "Part 4", kanji: "皮", kana: "かわ", romaji: "kawa", hanviet: "Bì", meaning: "Da, vỏ", example: "りんごの皮をむいて食べる。" },

  { id: 81, unit: "Unit 1", part: "Part 5", kanji: "缶", kana: "かん", romaji: "kan", hanviet: "Phẫu", meaning: "Lon, hộp thiếc", example: "おかしをカンに入れて保存する。" },
  { id: 82, unit: "Unit 1", part: "Part 5", kanji: "画面", kana: "がめん", romaji: "gamen", hanviet: "Họa Diện", meaning: "Màn hình", example: "パソコンの画面をずっと見ていると、目が疲れる。" },
  { id: 83, unit: "Unit 1", part: "Part 5", kanji: "番組", kana: "ばんぐみ", romaji: "bangumi", hanviet: "Phiên Tổ", meaning: "Chương trình (TV, radio)", example: "テレビの番組を見る。" },
  { id: 84, unit: "Unit 1", part: "Part 5", kanji: "記事", kana: "きじ", romaji: "kiji", hanviet: "Ký Sự", meaning: "Bài báo, tin tức", example: "この記事によると、日本に住む外国人が増えているそうだ。" },
  { id: 85, unit: "Unit 1", part: "Part 5", kanji: "近所", kana: "きんじょ", romaji: "kinjo", hanviet: "Cận Sở", meaning: "Hàng xóm, vùng lân cận", example: "近所の人とは仲良くしたほうがいい。" },
  { id: 86, unit: "Unit 1", part: "Part 5", kanji: "警察", kana: "けいさつ", romaji: "けいさつ", hanviet: "Cảnh Sát", meaning: "Cảnh sát", example: "自転車を盗まれたので、警察に届けた。" },
  { id: 87, unit: "Unit 1", part: "Part 5", kanji: "犯人", kana: "はんにん", romaji: "hannin", hanviet: "Phạm Nhân", meaning: "Thủ phạm, phạm nhân", example: "事件の犯人をつかまえる。" },
  { id: 88, unit: "Unit 1", part: "Part 5", kanji: "小銭", kana: "こぜに", romaji: "kozeni", hanviet: "Tiểu Tiền", meaning: "Tiền lẻ", example: "バスに乗ってから小銭がないことに気がつき、とても困った。" },
  { id: 89, unit: "Unit 1", part: "Part 5", kanji: "ごちそう", kana: "gochisou", romaji: "gochisou", hanviet: "", meaning: "Tiệc chiêu đãi, món ngon", example: "家族みんなでごちそうを食べて、祖父の誕生日を祝った。" },
  { id: 90, unit: "Unit 1", part: "Part 5", kanji: "作者", kana: "さくしゃ", romaji: "sakusha", hanviet: "Tác Giả", meaning: "Tác giả", example: "「ハムレット」の作者はシェイクスピアです。" },
  { id: 91, unit: "Unit 1", part: "Part 5", kanji: "作品", kana: "さくひん", romaji: "sakuhin", hanviet: "Tác Phẩm", meaning: "Tác phẩm", example: "学生の作品をロビーに展示する。" },
  { id: 92, unit: "Unit 1", part: "Part 5", kanji: "制服", kana: "せいふく", romaji: "seifuku", hanviet: "Chế Phục", meaning: "Đồng phục", example: "日本の中学校には制服のある学校が多い。" },
  { id: 93, unit: "Unit 1", part: "Part 5", kanji: "洗剤", kana: "せんざい", romaji: "senzai", hanviet: "Tẩy Tễ", meaning: "Chất tẩy rửa", example: "洗剤で食器を洗う。" },
  { id: 94, unit: "Unit 1", part: "Part 5", kanji: "底", kana: "そこ", romaji: "soko", hanviet: "Để", meaning: "Đáy", example: "くつの底に穴があu。" },
  { id: 95, unit: "Unit 1", part: "Part 5", kanji: "地下", kana: "ちか", romaji: "chika", hanviet: "Địa Hạ", meaning: "Tầng hầm, dưới đất", example: "大都市は地下の開発が進んでいる。" },
  { id: 96, unit: "Unit 1", part: "Part 5", kanji: "寺", kana: "てら", romaji: "tera", hanviet: "Tự", meaning: "Chùa", example: "寺にまいりする。" },
  { id: 97, unit: "Unit 1", part: "Part 5", kanji: "道路", kana: "どうろ", romaji: "douro", hanviet: "Đạo Lộ", meaning: "Con đường", example: "道路が込む。" },
  { id: 98, unit: "Unit 1", part: "Part 5", kanji: "坂", kana: "さか", romaji: "saka", hanviet: "Phản", meaning: "Dốc", example: "坂を上る。" },
  { id: 99, unit: "Unit 1", part: "Part 5", kanji: "煙", kana: "けむり", romaji: "kemuri", hanviet: "Yên", meaning: "Khói", example: "「火事のときは、煙に注意して逃げてください」" },
  { id: 100, unit: "Unit 1", part: "Part 5", kanji: "灰", kana: "はい", romaji: "hai", hanviet: "Hôi", meaning: "Tro", example: "紙が燃えて灰になる。" },

  { id: 101, unit: "Unit 1", part: "Part 6", kanji: "判", kana: "はん", romaji: "han", hanviet: "Phán", meaning: "Con dấu", example: "書類に判を押す。" },
  { id: 102, unit: "Unit 1", part: "Part 6", kanji: "名刺", kana: "めいし", romaji: "meishi", hanviet: "Danh Thứ", meaning: "Danh thiếp", example: "名刺を交換する。" },
  { id: 103, unit: "Unit 1", part: "Part 6", kanji: "免許", kana: "めんきょ", romaji: "menkyo", hanviet: "Miễn Hứa", meaning: "Giấy phép", example: "レストランを開くには、調理師の免許が必要だ。" },
  { id: 104, unit: "Unit 1", part: "Part 6", kanji: "多く", kana: "おおく", romaji: "ooku", hanviet: "Đa", meaning: "Nhiều", example: "オリンピックには多くの国が参加した。" },
  { id: 105, unit: "Unit 1", part: "Part 6", kanji: "前半", kana: "ぜんはん", romaji: "zenhan", hanviet: "Tiền Bán", meaning: "Nửa đầu", example: "映画の前半はたいくつだったが、後半はおもしろかった。" },
  { id: 106, unit: "Unit 1", part: "Part 6", kanji: "後半", kana: "こうはん", romaji: "kouはん", hanviet: "Hậu Bán", meaning: "Nửa sau", example: "映画の前半はたいくつだったg、後半はおもしろかった。" },
  { id: 107, unit: "Unit 1", part: "Part 6", kanji: "最高", kana: "さいこう", romaji: "saikou", hanviet: "Tối Cao", meaning: "Cao nhất, tuyệt nhất", example: "今日は今までの人生で最高の日だ。" },
  { id: 108, unit: "Unit 1", part: "Part 6", kanji: "最低", kana: "さいてい", romaji: "saitei", hanviet: "Tối Đê", meaning: "Thấp nhất, tồi nhất", example: "クラスで最低の点をとってしまった。" },
  { id: 109, unit: "Unit 1", part: "Part 6", kanji: "最初", kana: "さいしょ", romaji: "saisho", hanviet: "Tối Sơ", meaning: "Đầu tiên", example: "最初にひらがなを、次にカタカナを勉強した。" },
  { id: 110, unit: "Unit 1", part: "Part 6", kanji: "最后", kana: "さいご", romaji: "saigo", hanviet: "Tối Hậu", meaning: "Cuối cùng", example: "日本に来たばかりのころ、最初は何もわarrなかった。" },
  { id: 111, unit: "Unit 1", part: "Part 6", kanji: "自動", kana: "じどう", romaji: "jidou", hanviet: "Tự Động", meaning: "Tự động", example: "このドアは自動だから、手で開けなくてもいい。" },
  { id: 112, unit: "Unit 1", part: "Part 6", kanji: "種類", kana: "しゅゅるい", romaji: "shurui", hanviet: "Chủng Loại", meaning: "Loại, chủng loại", example: "公園にはいろいろな種類の花がある。" },
  { id: 113, unit: "Unit 1", part: "Part 6", kanji: "性格", kana: "せいかく", romaji: "seikaku", hanviet: "Tính Cách", meaning: "Tính cách", example: "あの人は性格がいいので、みんなに好かれている。" },
  { id: 114, unit: "Unit 1", part: "Part 6", kanji: "性質", kana: "せいしつ", romaji: "seishitsu", hanviet: "Tính Chất", meaning: "Tính chất, đặc tính", example: "この布は燃えにくい性質を持っている。" },
  { id: 115, unit: "Unit 1", part: "Part 6", kanji: "順番", kana: "じゅんばん", romaji: "junban", hanviet: "Thuận Phiên", meaning: "Thứ tự, lần lượt", example: "発表の順番を決める。" },
  { id: 116, unit: "Unit 1", part: "Part 6", kanji: "番", kana: "ばん", romaji: "ban", hanviet: "Phiên", meaning: "Lượt", example: "次は私の番だ。" },
  { id: 117, unit: "Unit 1", part: "Part 6", kanji: "方法", kana: "ほうほう", romaji: "houhou", hanviet: "Phương Pháp", meaning: "Phương pháp, cách thức", example: "いい方法を探す。" },
  { id: 118, unit: "Unit 1", part: "Part 6", kanji: "製品", kana: "せいひん", romaji: "seihin", hanviet: "Chế Phẩm", meaning: "Sản phẩm, hàng hóa", example: "完成した製品を検査する。" },
  { id: 119, unit: "Unit 1", part: "Part 6", kanji: "値上がり", kana: "ねあがり", romaji: "neagari", hanviet: "Trị Thượng", meaning: "Tăng giá", example: "食品の値上がり。" },
  { id: 120, unit: "Unit 1", part: "Part 6", kanji: "生", kana: "生", romaji: "nama", hanviet: "Sinh", meaning: "Tươi sống", example: "生の魚。" },

  // --- UNIT 2 ---
  { id: 121, unit: "Unit 2", part: "Part 1", kanji: "渇く", kana: "かわく", romaji: "kawaku", hanviet: "Khát", meaning: "Khát", example: "のどがかわいた。" },
  { id: 122, unit: "Unit 2", part: "Part 1", kanji: "嗅ぐ", kana: "かぐ", romaji: "kagu", hanviet: "Khứu", meaning: "Ngửi", example: "においをかぐ。" },
  { id: 123, unit: "Unit 2", part: "Part 1", kanji: "叩く", kana: "たたた", romaji: "tataku", hanviet: "Khấu", meaning: "Vỗ, đánh, gõ", example: "子供のおしりをたたく。" },
  { id: 124, unit: "Unit 2", part: "Part 1", kanji: "殴る", kana: "なぐる", romaji: "naguru", hanviet: "Ẩu", meaning: "Đấm", example: "教師が生徒をなぐって、問題になっている。" },
  { id: 125, unit: "Unit 2", part: "Part 1", kanji: "蹴る", kana: "ける", romaji: "keru", hanviet: "Xúc", meaning: "Đá", example: "ボールをける。" },
  { id: 126, unit: "Unit 2", part: "Part 1", kanji: "抱く", kana: "だく", romaji: "daku", hanviet: "Bão", meaning: "Ôm", example: "子供を両手でしっかりと抱く。" },
  { id: 127, unit: "Unit 2", part: "Part 1", kanji: "倒れる", kana: "たおれる", romaji: "taoreru", hanviet: "Đảo", meaning: "Đổ, ngã", example: "台風で木が倒れた。" },
  { id: 128, unit: "Unit 2", part: "Part 1", kanji: "倒す", kana: "たおす", romaji: "taosu", hanviet: "Đảo", meaning: "Làm đổ, đánh bại", example: "花びんを倒して割ってしまった。" },
  { id: 129, unit: "Unit 2", part: "Part 1", kanji: "起きる", kana: "おきる", romaji: "okiru", hanviet: "Khởi", meaning: "Thức dậy, xảy ra", example: "きょうは8時に起きた。" },
  { id: 130, unit: "Unit 2", part: "Part 1", kanji: "起こす", kana: "おこす", romaji: "okosuu", hanviet: "Khởi", meaning: "Đánh thức, gây ra", example: "うちの子は朝起こしてもなかなか起きない。" },
  { id: 131, unit: "Unit 2", part: "Part 1", kanji: "尋ねる", kana: "たずねる", romaji: "tazuneru", hanviet: "Tầm", meaning: "Hỏi", example: "交番で警官に市役所までの道をたずねた。" },
  { id: 132, unit: "Unit 2", part: "Part 1", kanji: "呼ぶ", kana: "よぶ", romaji: "yobu", hanviet: "Hô", meaning: "Gọi", example: "「名前を呼ばれたら返事をしてください」" },
  { id: 133, unit: "Unit 2", part: "Part 1", kanji: "叫ぶ", kana: "さけぶ", romaji: "sakebu", hanviet: "Khiếu", meaning: "Gào, hét", example: "大声で叫んだが、相手は気づかずに行ってしまった。" },
  { id: 134, unit: "Unit 2", part: "Part 1", kanji: "黙る", kana: "だまる", romaji: "damaru", hanviet: "Mặc", meaning: "Im lặng", example: "先生が質問したが、だれも答えないでだまっている。" },
  { id: 135, unit: "Unit 2", part: "Part 1", kanji: "飼う", kana: "かう", romaji: "kau", hanviet: "Tự", meaning: "Nuôi (thú cưng)", example: "何かペットを飼いたいと思っている。" },
  { id: 136, unit: "Unit 2", part: "Part 1", kanji: "数える", kana: "かぞえる", romaji: "kazoeru", hanviet: "Số", meaning: "Đếm", example: "数を数える。" },
  { id: 137, unit: "Unit 2", part: "Part 1", kanji: "乾く", kana: "かわく", romaji: "kawaku", hanviet: "Can", meaning: "Khô", example: "風が強かったので、外に干した洗濯物はすぐに乾いた。" },
  { id: 138, unit: "Unit 2", part: "Part 1", kanji: "乾かす", kana: "かわかす", romaji: "kawakasu", hanviet: "Can", meaning: "Làm khô", example: "ドライヤーでぬれた髪を乾かした。" },
  { id: 139, unit: "Unit 2", part: "Part 1", kanji: "畳む", kana: "たたむ", romaji: "tatamu", hanviet: "Điệp", meaning: "Gấp", example: "洗濯物をたたむ。" },
  { id: 140, unit: "Unit 2", part: "Part 1", kanji: "誘う", kana: "さそう", romaji: "sasou", hanviet: "Dụ", meaning: "Mới, rủ", example: "友だちを誘って映画を見に行った。" },

  { id: 141, unit: "Unit 2", part: "Part 2", kanji: "奢る", kana: "おごる", romaji: "ogoru", hanviet: "Sa", meaning: "Khao, đãi", example: "きのうは後輩に焼き肉をおごった。" },
  { id: 142, unit: "Unit 2", part: "Part 2", kanji: "預かる", kana: "あずかる", romaji: "azukaru", hanviet: "Dự", meaning: "Trông nom, chăm sóc", example: "旅行に行く友だちから犬を預かることになった。" },
  { id: 143, unit: "Unit 2", part: "Part 2", kanji: "預ける", kana: "あずける", romaji: "azukeru", hanviet: "Dự", meaning: "Gửi, giao phó", example: "銀行にお金を預けると、利子がつく。" },
  { id: 144, unit: "Unit 2", part: "Part 2", kanji: "決まる", kana: "きまる", romaji: "kimaru", hanviet: "Quyết", meaning: "Được quyết định", example: "帰国の日が決まった。" },
  { id: 145, unit: "Unit 2", part: "Part 2", kanji: "決める", kana: "きめる", romaji: "kimeru", hanviet: "Quyết", meaning: "Quyết định", example: "「進学か就職か、早く決めたほうがいいですよ」" },
  { id: 146, unit: "Unit 2", part: "Part 2", kanji: "写る", kana: "うつる", romaji: "utsuru", hanviet: "Tả", meaning: "Chụp được, chiếu", example: "このカメラは暗いところでもよく写る。" },
  { id: 147, unit: "Unit 2", part: "Part 2", kanji: "写す", kana: "うつす", romaji: "utsusu", hanviet: "Tả", meaning: "Chụp, sao chép", example: "写真を写す。" },
  { id: 148, unit: "Unit 2", part: "Part 2", kanji: "思い出す", kana: "おもいだす", romaji: "omoidasu", hanviet: "Tư Xuất", meaning: "Nhớ lại", example: "毎年春になると、高校の入学式を思い出します。" },
  { id: 149, unit: "Unit 2", part: "Part 2", kanji: "教わる", kana: "おそわる", romaji: "osowaru", hanviet: "Giáo", meaning: "Được dạy", example: "この料理の作り方は母に教わりました。" },
  { id: 150, unit: "Unit 2", part: "Part 2", kanji: "申し込む", kana: "もうしこむ", romaji: "moushikomu", hanviet: "Thân Thâu", meaning: "Đăng ký", example: "パーティーに参加を申し込む。" },
  { id: 151, unit: "Unit 2", part: "Part 2", kanji: "断る", kana: "ことわる", romaji: "kotowaru", hanviet: "Đoạn", meaning: "Từ chối", example: "頼まれた仕事を断った。" },
  { id: 152, unit: "Unit 2", part: "Part 2", kanji: "見つかる", kana: "みつかる", romaji: "mitsukaru", hanviet: "Kiến", meaning: "Tìm thấy, bị bắt gặp", example: "なくなったと思っていた指輪が、ソファーの下で見つかった。" },
  { id: 153, unit: "Unit 2", part: "Part 2", kanji: "見つける", kana: "みつける", romaji: "mitsukeru", hanviet: "Kiến", meaning: "Tìm thấy", example: "なくなったと思っていた指輪を、ソファーの下で見つけた。" },
  { id: 154, unit: "Unit 2", part: "Part 2", kanji: "捕まる", kana: "つかまる", romaji: "tsukamaru", hanviet: "Bộ", meaning: "Bị bắt, nắm vào", example: "犯人が警察に捕まった。" },
  { id: 155, unit: "Unit 2", part: "Part 2", kanji: "捕まえる", kana: "つかまえる", romaji: "tsukamaeru", hanviet: "Bộ", meaning: "Bắt giữ", example: "警察が泥棒を捕まえた。" },
  { id: 156, unit: "Unit 2", part: "Part 2", kanji: "乗る", kana: "のる", romaji: "noru", hanviet: "Thừa", meaning: "Lên xe, cưỡi", example: "毎朝、電車に乗って学校に通っている。" },
  { id: 157, unit: "Unit 2", part: "Part 2", kanji: "乗せる", kana: "のせる", romaji: "noseru", hanviet: "Thừa", meaning: "Cho lên xe, chở", example: "子どもuを車に乗せて、学校まで送って行った。" },
  { id: 158, unit: "Unit 2", part: "Part 2", kanji: "降りる", kana: "おりる", romaji: "oriru", hanviet: "Giáng", meaning: "Xuống xe", example: "電車を降りる。" },
  { id: 159, unit: "Unit 2", part: "Part 2", kanji: "降ろす", kana: "おろす", romaji: "orosu", hanviet: "Giáng", meaning: "Cho xuống xe, rút tiền", example: "「あの銀行の前で降ろしてください」" },
  { id: 160, unit: "Unit 2", part: "Part 2", kanji: "直る", kana: "なおる", romaji: "naoru", hanviet: "Trực", meaning: "Được sửa", example: "こわれたパソコンが直った。" },

  { id: 161, unit: "Unit 2", part: "Part 3", kanji: "直す", kana: "なおす", romaji: "naosu", hanviet: "Trực", meaning: "Sửa chữa, dịch", example: "こわれた時計を直す。" },
  { id: 162, unit: "Unit 2", part: "Part 3", kanji: "治る", kana: "なおる", romaji: "naoru", hanviet: "Trị", meaning: "Khỏi bệnh", example: "なかなか頭痛が治らない。" },
  { id: 163, unit: "Unit 2", part: "Part 3", kanji: "治す", kana: "なおす", romaji: "naosu", hanviet: "Trị", meaning: "Chữa bệnh", example: "「よく休んで早くかぜを治してください」" },
  { id: 164, unit: "Unit 2", part: "Part 3", kanji: "亡くなる", kana: "なくなる", romaji: "nakunaru", hanviet: "Vong", meaning: "Mất, qua đời", example: "社長が90歳でなくなった。" },
  { id: 165, unit: "Unit 2", part: "Part 3", kanji: "亡くす", kana: "なくす", romaji: "nakusu", hanviet: "Vong", meaning: "Mất (người thân)", example: "彼は子どものとき、父親をなくした。" },
  { id: 166, unit: "Unit 2", part: "Part 3", kanji: "生まれる", kana: "うまれる", romaji: "umareru", hanviet: "Sinh", meaning: "Được sinh ra", example: "先月子どもが生まれた。" },
  { id: 167, unit: "Unit 2", part: "Part 3", kanji: "産む", kana: "うむ", romaji: "umu", hanviet: "Sán", meaning: "Sinh đẻ", example: "妻が先日元気な女の子を産んだ。" },
  { id: 168, unit: "Unit 2", part: "Part 3", kanji: "出会う", kana: "であう", romaji: "deau", hanviet: "Xuất Hội", meaning: "Gặp gỡ ngẫu nhiên", example: "駅で偶然大学時代の友人と出会った。" },
  { id: 169, unit: "Unit 2", part: "Part 3", kanji: "訪ねる", kana: "たずねる", romaji: "tazuneru", hanviet: "Phỏng", meaning: "Ghé thăm", example: "友人の家を訪ねた。" },
  { id: 170, unit: "Unit 2", part: "Part 3", kanji: "付き合う", kana: "つきあう", romaji: "tsukiau", hanviet: "Phó Hợp", meaning: "Kết giao, hẹn hò", example: "隣の家の人と親しく付き合っている。" },
  { id: 171, unit: "Unit 2", part: "Part 3", kanji: "効く", kana: "きく", romaji: "kiku", hanviet: "Hiệu", meaning: "Có hiệu quả", example: "この薬は頭痛によく効く。" },
  { id: 172, unit: "Unit 2", part: "Part 3", kanji: "流行る", kana: "はやる", romaji: "hayaru", hanviet: "Lưu Hành", meaning: "Thịnh hành, lan rộng", example: "この冬は赤い色が流行っている。" },
  { id: 173, unit: "Unit 2", part: "Part 3", kanji: "経つ", kana: "たつ", romaji: "tatsu", hanviet: "Kinh", meaning: "Trải qua (thời gian)", example: "日本へ来てから10年が経った。" },
  { id: 174, unit: "Unit 2", part: "Part 3", kanji: "間に合う", kana: "まニアう", romaji: "maniau", hanviet: "Gian Hợp", meaning: "Kịp thời", example: "電車が遅れたが、なんとか授業に間に合った。" },
  { id: 175, unit: "Unit 2", part: "Part 3", kanji: "間に合わせる", kana: "まニアわせる", romaji: "maniawaseru", hanviet: "Gian Hợp", meaning: "Làm cho kịp", example: "レポートを、がんばって締め切りに間に合わせた。" },
  { id: 176, unit: "Unit 2", part: "Part 3", kanji: "通う", kana: "かよう", romaji: "kayou", hanviet: "Thông", meaning: "Đi lại thường xuyên", example: "学校に通う。" },
  { id: 177, unit: "Unit 2", part: "Part 3", kanji: "込む", kana: "こむ", romaji: "komu", hanviet: "Vận", meaning: "Đông đúc", example: "電車が込む。" },
  { id: 178, unit: "Unit 2", part: "Part 3", kanji: "すれ違う", kana: "すれちがう", romaji: "surechigau", hanviet: "Vi", meaning: "Đi ngang qua nhau", example: "この道はせmaiので、自動車がすれ違うのは大変だ。" },
  { id: 179, unit: "Unit 2", part: "Part 3", kanji: "掛かる", kana: "かかる", romaji: "kakaru", hanviet: "Quải", meaning: "Tốn, mất, treo", example: "this サラダには何もかかっていないようだ。" },
  { id: 180, unit: "Unit 2", part: "Part 3", kanji: "掛ける", kana: "かける", romaji: "kakeru", hanviet: "Quải", meaning: "Treo, đeo, đắp", example: "料理にしょうゆをかけて食べる。" },

  { id: 181, unit: "Unit 2", part: "Part 4", kanji: "動く", kana: "うごく", romaji: "ugoku", hanviet: "Động", meaning: "Chuyển động, hoạt động", example: "「写真を撮るから動かないでください」" },
  { id: 182, unit: "Unit 2", part: "Part 4", kanji: "動かす", kana: "うごかす", romaji: "ugokasu", hanviet: "Động", meaning: "Làm cho chuyển động", example: "ひどいけがをして、体を動かすこともできない。" },
  { id: 183, unit: "Unit 2", part: "Part 4", kanji: "離れる", kana: "はなれる", romaji: "hanareru", hanviet: "Ly", meaning: "Rời xa, cách xa", example: "「危ないから、ストーブから離れて遊びなさい」" },
  { id: 184, unit: "Unit 2", part: "Part 4", kanji: "離す", kana: "はなす", romaji: "hanasu", hanviet: "Ly", meaning: "Để xa ra, tách ra", example: "テストのときは、机を離して並べる。" },
  { id: 185, unit: "Unit 2", part: "Part 4", kanji: "ぶつかる", kana: "butsukaru", romaji: "butsukaru", hanviet: "", meaning: "Va chạm, đâm vào", example: "道で自転車にぶつかってけがをした。" },
  { id: 186, unit: "Unit 2", part: "Part 4", kanji: "ぶつける", kana: "butsukeru", romaji: "butsukeru", hanviet: "", meaning: "Đâm vào, húc vào", example: "運転していて、車を電柱にぶつけてしまった。" },
  { id: 187, unit: "Unit 2", part: "Part 4", kanji: "こぼれる", kana: "koboreru", romaji: "koboreru", hanviet: "", meaning: "Bị tràn, bị đổ", example: "手がふるえてお茶がこぼれてしまった。" },
  { id: 188, unit: "Unit 2", part: "Part 4", kanji: "こぼす", kana: "kobosu", romaji: "kobosu", hanviet: "", meaning: "Làm tràn, làm đổ", example: "コップを倒して水をこぼしてしまった。" },
  { id: 189, unit: "Unit 2", part: "Part 4", kanji: "拭く", kana: "ふく", romaji: "fuku", hanviet: "Thức", meaning: "Lau, chùi", example: "汗を拭く。" },
  { id: 190, unit: "Unit 2", part: "Part 4", kanji: "片付く", kana: "かたづく", romaji: "kataduku", hanviet: "Phiến Phó", meaning: "Được dọn dẹp", example: "大掃除をして、やっと部屋が片付いた。" },
  { id: 191, unit: "Unit 2", part: "Part 4", kanji: "片付ける", kana: "かたづける", romaji: "katadukeru", hanviet: "Phiến Phó", meaning: "Dọn dẹp", example: "机の上을片付ける。" },
  { id: 192, unit: "Unit 2", part: "Part 4", kanji: "包む", kana: "つつむ", romaji: "tsutsumu", hanviet: "Bao", meaning: "Gói, bọc", example: "プレゼントをきれいな紙で包む。" },
  { id: 193, unit: "Unit 2", part: "Part 4", kanji: "張る", kana: "はる", romaji: "haru", hanviet: "Trương", meaning: "Dán", example: "壁にポスターを張る。" },
  { id: 194, unit: "Unit 2", part: "Part 4", kanji: "無くなる", kana: "なくなる", romaji: "nakunaru", hanviet: "Vô", meaning: "Bị mất, hết", example: "部屋のかぎがなくなってしまった。" },
  { id: 195, unit: "Unit 2", part: "Part 4", kanji: "無くす", kana: "なくす", romaji: "nakusu", hanviet: "Vô", meaning: "Làm mất", example: "パスポートをなくして困っている。" },
  { id: 196, unit: "Unit 2", part: "Part 4", kanji: "足りる", kana: "たりる", romaji: "tariru", hanviet: "Túc", meaning: "Đầy đủ", example: "この収入では生活するのに全然足りない。" },
  { id: 197, unit: "Unit 2", part: "Part 4", kanji: "残る", kana: "のこる", romaji: "nokoru", hanviet: "Tàn", meaning: "Còn lại, sót lại", example: "料理を作りすぎて、たくさん残ってしまった。" },
  { id: 198, unit: "Unit 2", part: "Part 4", kanji: "残す", kana: "のこす", romaji: "nokosu", hanviet: "Tàn", meaning: "Để lại", example: "ごはんを残してしまった。" },
  { id: 199, unit: "Unit 2", part: "Part 4", kanji: "腐る", kana: "くさる", romaji: "kusaru", hanviet: "Hủ", meaning: "Thối, thiu, hỏng", example: "腐ったものを食べて、おなかを壊してしまった。" },
  { id: 200, unit: "Unit 2", part: "Part 4", kanji: "剥ける", kana: "むける", romaji: "mukeru", hanviet: "Bác", meaning: "Bị lột, bong ra", example: "海で日焼けをして、背中の皮がむけた。" },

  { id: 201, unit: "Unit 2", part: "Part 5", kanji: "剥く", kana: "むく", romaji: "muku", hanviet: "Bác", meaning: "Gọt, lột, bóc", example: "果物の皮をむく。" },
  { id: 202, unit: "Unit 2", part: "Part 5", kanji: "滑る", kana: "すべる", romaji: "suberu", hanviet: "Hoạt", meaning: "Trượt", example: "新しいスケート場はきれいで、楽しくすべることができた。" },
  { id: 203, unit: "Unit 2", part: "Part 5", kanji: "積もる", kana: "つもる", romaji: "tsumoru", hanviet: "Tích", meaning: "Chất đống, tích tụ", example: "きのう降った雪が積もっている。" },
  { id: 204, unit: "Unit 2", part: "Part 5", kanji: "積む", kana: "つむ", romaji: "tsumu", hanviet: "Tích", meaning: "Chất, xếp, tích lũy", example: "机の上に本がたくさん積んである。" },
  { id: 205, unit: "Unit 2", part: "Part 5", kanji: "空く", kana: "あく", romaji: "aku", hanviet: "Không", meaning: "Trống, hở, vắng", example: "くつのしたに穴が空いてしまった。" },
  { id: 206, unit: "Unit 2", part: "Part 5", kanji: "空ける", kana: "あける", romaji: "akeru", hanviet: "Không", meaning: "Làm trống, để cách", example: "かべに穴を空ける。" },
  { id: 207, unit: "Unit 2", part: "Part 5", kanji: "下がる", kana: "さがる", romaji: "sagaru", hanviet: "Hạ", meaning: "Hạ xuống, giảm đi", example: "熱が下がる。" },
  { id: 208, unit: "Unit 2", part: "Part 5", kanji: "下げる", kana: "さげる", romaji: "sageru", hanviet: "Hạ", meaning: "Làm hạ xuống, giảm", example: "熱を下げる。" },
  { id: 209, unit: "Unit 2", part: "Part 5", kanji: "冷える", kana: "ひえる", romaji: "hieru", hanviet: "Lãnh", meaning: "Lạnh đi, nguội đi", example: "寒いところに長くいたので、手足が冷えてしまった。" },
  { id: 210, unit: "Unit 2", part: "Part 5", kanji: "冷やす", kana: "ひやす", romaji: "hiyasu", hanviet: "Lãnh", meaning: "Làm lạnh", example: "この果物は冷やして食べたほうがいい。" },
  { id: 211, unit: "Unit 2", part: "Part 5", kanji: "冷める", kana: "さめる", romaji: "sameru", hanviet: "Lãnh", meaning: "Nguội đi, mất hứng", example: "this 料理は冷めるとおいしくない。" },
  { id: 212, unit: "Unit 2", part: "Part 5", kanji: "冷ます", kana: "さます", romaji: "samasu", hanviet: "Lãnh", meaning: "Làm nguội", example: "お風呂のお湯が熱くなりすぎた。少し冷ましてから入ろう。" },
  { id: 213, unit: "Unit 2", part: "Part 5", kanji: "燃える", kana: "もえる", romaji: "moeru", hanviet: "Nhiên", meaning: "Cháy", example: "火で紙が燃える。" },
  { id: 214, unit: "Unit 2", part: "Part 5", kanji: "燃やす", kana: "もやす", romaji: "moyasu", hanviet: "Nhiên", meaning: "Đốt, thiêu", example: "火で紙を燃やす。" },
  { id: 215, unit: "Unit 2", part: "Part 5", kanji: "沸く", kana: "わく", romaji: "waku", hanviet: "Phí", meaning: "Sôi", example: "湯が沸く。" },
  { id: 216, unit: "Unit 2", part: "Part 5", kanji: "沸かす", kana: "わかす", romaji: "wakasu", hanviet: "Phí", meaning: "Đun sôi", example: "湯を沸かす。" },
  { id: 217, unit: "Unit 2", part: "Part 5", kanji: "鳴る", kana: "なる", romaji: "naru", hanviet: "Minh", meaning: "Kêu, reo", example: "雷が鳴っている。" },
  { id: 218, unit: "Unit 2", part: "Part 5", kanji: "鳴らす", kana: "ならす", romaji: "narasu", hanviet: "Minh", meaning: "Làm cho kêu, reo", example: "ブザーを鳴らす。" },
  { id: 219, unit: "Unit 2", part: "Part 5", kanji: "役立つ", kana: "やくだつ", romaji: "yakudatsu", hanviet: "Dịch Lập", meaning: "Có ích", example: "インターネットの情報は、勉強や仕事に役立つ。" },
  { id: 220, unit: "Unit 2", part: "Part 5", kanji: "役立てる", kana: "やくだてる", romaji: "yakudateru", hanviet: "Dịch Lập", meaning: "Đưa vào sử dụng, ứng dụng", example: "インターネットの情報を、勉強や仕事に役立てる。" },

  { id: 221, unit: "Unit 2", part: "Part 6", kanji: "飾り", kana: "かざり", romaji: "kazari", hanviet: "Sức", meaning: "Đồ trang trí", example: "クリsmases の飾りを買った。" },
  { id: 222, unit: "Unit 2", part: "Part 6", kanji: "遊び", kana: "あそび", romaji: "asobi", hanviet: "Du", meaning: "Trò chơi, vui chơi", example: "かくれんぼは子どもの遊びだ。" },
  { id: 223, unit: "Unit 2", part: "Part 6", kanji: "集まり", kana: "あつまり", romaji: "atsumari", hanviet: "Tập", meaning: "Cuộc họp, sự tập trung", example: "あした、マンションの住人の集まりがある。" },
  { id: 224, unit: "Unit 2", part: "Part 6", kanji: "教え", kana: "おしえ", romaji: "oshie", hanviet: "Giáo", meaning: "Lời dạy", example: "母の教えを今でも思い出す。" },
  { id: 225, unit: "Unit 2", part: "Part 6", kanji: "踊り", kana: "おどり", romaji: "odori", hanviet: "Dũng", meaning: "Điệu nhảy", example: "留学生が各国の踊りを踊った。" },
  { id: 226, unit: "Unit 2", part: "Part 6", kanji: "思い", kana: "おmoi", romaji: "omoi", hanviet: "Tư", meaning: "Suy nghĩ, cảm xúc", example: "あの人に私の思いが届いた。" },
  { id: 227, unit: "Unit 2", part: "Part 6", kanji: "考え", kana: "かんがえ", romaji: "kangae", hanviet: "Khảo", meaning: "Suy nghĩ, ý tưởng", example: "私にいい考えがある。" },
  { id: 228, unit: "Unit 2", part: "Part 6", kanji: "片づけ", kana: "かたづけ", romaji: "kataduke", hanviet: "Phiến Phó", meaning: "Việc dọn dẹp", example: "私は片づけが苦手だ。" },
  { id: 229, unit: "Unit 2", part: "Part 6", kanji: "手伝い", kana: "てつだい", romaji: "tetsudai", hanviet: "Thủ Truyền", meaning: "Sự giúp đỡ", example: "引っ越しの手伝いをする。" },
  { id: 230, unit: "Unit 2", part: "Part 6", kanji: "働き", kana: "はたらき", romaji: "hataraki", hanviet: "Động", meaning: "Hoạt động, chức năng", example: "血液の働きの一つは、体に栄養を運ぶことだ。" },
  { id: 231, unit: "Unit 2", part: "Part 6", kanji: "決まり", kana: "きまり", romaji: "kimari", hanviet: "Quyết", meaning: "Quy định, quy tắc", example: "学校で新しい決まりが作られた。" },
  { id: 232, unit: "Unit 2", part: "Part 6", kanji: "騒ぎ", kana: "さわぎ", romaji: "sawagi", hanviet: "Tào", meaning: "Sự ồn ào, náo loạn", example: "きのう、駅前で騒ぎがあった。" },
  { id: 233, unit: "Unit 2", part: "Part 6", kanji: "知らせ", kana: "しらせ", romaji: "shirase", hanviet: "Tri", meaning: "Thông báo, tin tức", example: "父が入院したという知らせがあった。" },
  { id: 234, unit: "Unit 2", part: "Part 6", kanji: "頼み", kana: "たのみ", romaji: "tanomi", hanviet: "Lại", meaning: "Lời nhờ vả, yêu cầu", example: "「あなたに頼みがあるんです」" },
  { id: 235, unit: "Unit 2", part: "Part 6", kanji: "疲れ", kana: "つかれ", romaji: "tsukare", hanviet: "Bì", meaning: "Sự mệt mỏi", example: "仕事で疲れがたまっている。" },
  { id: 236, unit: "Unit 2", part: "Part 6", kanji: "違い", kana: "違い", romaji: "chigai", hanviet: "Vi", meaning: "Sự khác biệt", example: "この二つの違いがわからない。" },
  { id: 237, unit: "Unit 2", part: "Part 6", kanji: "始め", kana: "はじめ", romaji: "hajime", hanviet: "Thủy", meaning: "Lúc bắt đầu", example: "本を始めから終わりまで全部読んだ。" },
  { id: 238, unit: "Unit 2", part: "Part 6", kanji: "続き", kana: "つづき", romaji: "tsuduki", hanviet: "Tục", meaning: "Sự tiếp tục, phần tiếp theo", example: "早く本の続きが読いたい。" },
  { id: 239, unit: "Unit 2", part: "Part 6", kanji: "暮れ", kana: "くれ", romaji: "kure", hanviet: "Mộ", meaning: "Cuối (năm), chiều tối", example: "年の暮れは忙しい。" },
  { id: 240, unit: "Unit 2", part: "Part 6", kanji: "行き", kana: "いき", romaji: "iki", hanviet: "Hành", meaning: "Chiều đi, hướng đi", example: "旅行は、行きは新幹線、帰りは飛行機だった。" },

  { id: 241, unit: "Unit 2", part: "Part 7", kanji: "帰り", kana: "かえり", romaji: "kaeri", hanviet: "Quy", meaning: "Chiều về", example: "帰りにコンビニに寄る。" },
  { id: 242, unit: "Unit 2", part: "Part 7", kanji: "急ぎ", kana: "いそぎ", romaji: "isogi", hanviet: "Cấp", meaning: "Việc gấp, sự vội vàng", example: "急ぎの仕事が入った。" },
  { id: 243, unit: "Unit 2", part: "Part 7", kanji: "遅れ", kana: "おくれ", romaji: "okure", hanviet: "Trì", meaning: "Sự chậm trễ, muộn", example: "電車に3分の遅れが出た。" },
  { id: 244, unit: "Unit 2", part: "Part 7", kanji: "貸し", kana: "かし", romaji: "kashi", hanviet: "Thải", meaning: "Việc cho vay", example: "あの人には10万円の貸しがある。" },
  { id: 245, unit: "Unit 2", part: "Part 7", kanji: "借り", kana: "かり", romaji: "kari", hanviet: "Tá", meaning: "Việc vay mượn", example: "借りは返さなければならない。" },
  { id: 246, unit: "Unit 2", part: "Part 7", kanji: "勝ち", kana: "かち", romaji: "kachi", hanviet: "Thắng", meaning: "Chiến thắng", example: "きょうの試合はAチームの勝ちだった。" },
  { id: 247, unit: "Unit 2", part: "Part 7", kanji: "負け", kana: "まけ", romaji: "make", hanviet: "Phụ", meaning: "Trận thua, thất bại", example: "負けが続いて、いやになった。" },
  { id: 248, unit: "Unit 2", part: "Part 7", kanji: "迎え", kana: "むかえ", romaji: "mukae", hanviet: "Nghênh", meaning: "Việc đón", example: "迎えの車がなかなか来ない。" },
  { id: 249, unit: "Unit 2", part: "Part 7", kanji: "始まり", kana: "はじまり", romaji: "hajimari", hanviet: "Thủy", meaning: "Sự bắt đầu", example: "映画の始まりに間に合わなかった。" },
  { id: 250, unit: "Unit 2", part: "Part 7", kanji: "終わり", kana: "おわり", romaji: "owari", hanviet: "Chung", meaning: "Sự kết thúc", example: "夏休みはもうすぐ終わりだ。" },
  { id: 251, unit: "Unit 2", part: "Part 7", kanji: "戻り", kana: "もどり", romaji: "modori", hanviet: "Lệ", meaning: "Việc quay lại", example: "「きょうの戻りは3時ごろになります」" },
  { id: 252, unit: "Unit 2", part: "Part 7", kanji: "別れ", kana: "わかれ", romaji: "wakare", hanviet: "Biệt", meaning: "Sự chia tay", example: "日本では3月は別れの季節だ。" },
  { id: 253, unit: "Unit 2", part: "Part 7", kanji: "喜び", kana: "よろこび", romaji: "yorokobi", hanviet: "Hỷ", meaning: "Niềm vui", example: "優勝できて、喜びでいっぱいだ。" },
  { id: 254, unit: "Unit 2", part: "Part 7", kanji: "楽しみ", kana: "たのしみ", romaji: "tanoshimi", hanviet: "Lạc", meaning: "Niềm vui, sự mong đợi", example: "来週のパーティーが楽しみだ。" },
  { id: 255, unit: "Unit 2", part: "Part 7", kanji: "笑い", kana: "わらい", romaji: "warai", hanviet: "Tiếu", meaning: "Tiếng cười", example: "歌手の冗談で会場に笑いが起きた。" },
  { id: 256, unit: "Unit 2", part: "Part 7", kanji: "驚き", kana: "おどろき", romaji: "odoroki", hanviet: "Kinh", meaning: "Sự ngạc nhiên", example: "this 大きな家がたったの100万円とは驚きだ。" },
  { id: 257, unit: "Unit 2", part: "Part 7", kanji: "怒り", kana: "いかり", romaji: "ikari", hanviet: "Nộ", meaning: "Cơn giận", example: "殺人のニュースに怒りを感じた。" },
  { id: 258, unit: "Unit 2", part: "Part 7", kanji: "悲しみ", kana: "かなしみ", romaji: "kanashimi", hanviet: "Bi", meaning: "Sự đau buồn", example: "愛犬を亡くした悲しみが消えない。" },

  // --- UNIT 3 ---
  { id: 259, unit: "Unit 3", part: "Part 1", kanji: "幸せな", kana: "しあわせな", romaji: "shiawasena", hanviet: "Hạnh", meaning: "Hạnh phúc", example: "幸せな人生。" },
  { id: 260, unit: "Unit 3", part: "Part 1", kanji: "得意な", kana: "とくいな", romaji: "tokuina", hanviet: "Đắc Ý", meaning: "Giỏi, đắc ý", example: "彼女はギターが得意だ。" },
  { id: 261, unit: "Unit 3", part: "Part 1", kanji: "苦手な", kana: "いがてな", romaji: "nigatena", hanviet: "Khổ Thủ", meaning: "Kém, yếu", example: "彼女はギターが苦手だ。" },
  { id: 262, unit: "Unit 3", part: "Part 1", kanji: "熱心な", kana: "ねっしんな", romaji: "nesshinna", hanviet: "Nhiệt Tâm", meaning: "Nhiệt tình", example: "熱心な仕事ぶりが認められて昇進した。" },
  { id: 263, unit: "Unit 3", part: "Part 1", kanji: "夢u中な", kana: "むちゅうな", romaji: "muchuuna", hanviet: "Mộng Trung", meaning: "Say mê", example: "子どものころ、SF漫画に夢中になった。" },
  { id: 264, unit: "Unit 3", part: "Part 1", kanji: "退屈な", kana: "たいくつな", romaji: "taikutsuna", hanviet: "Thoái Khuất", meaning: "Buồn chán", example: "ほかの観客は笑いながら見ていたが、私には退屈な映画だった。" },
  { id: 265, unit: "Unit 3", part: "Part 1", kanji: "健康な", kana: "けんこうな", romaji: "kenkouna", hanviet: "Kiện Khang", meaning: "Khỏe mạnh", example: "心も体も健康な子どもを育てたい。" },
  { id: 266, unit: "Unit 3", part: "Part 1", kanji: "苦しい", kana: "くるしい", romaji: "kurushii", hanviet: "Khổ", meaning: "Khổ cực, đau đớn", example: "息が苦しい。" },
  { id: 267, unit: "Unit 3", part: "Part 1", kanji: "平気な", kana: "へいきな", romaji: "heikina", hanviet: "Bình Khí", meaning: "Bình thản", example: "彼女は、どんなに悪口を言われても平気な顔をしている。" },
  { id: 268, unit: "Unit 3", part: "Part 1", kanji: "悔しい", kana: "くやしい", romaji: "kuyashii", hanviet: "Hối", meaning: "Đáng tiếc, cay cú", example: "たった1点差で試合に負けて悔しい思いをした。" },
  { id: 269, unit: "Unit 3", part: "Part 1", kanji: "羨ましい", kana: "うらやましい", romaji: "urayamashii", hanviet: "Tiện", meaning: "Ghen tị, thèm muốn", example: "才能の豊かな人がうらやましい。" },
  { id: 270, unit: "Unit 3", part: "Part 1", kanji: "痒い", kana: "かゆい", romaji: "kayui", hanviet: "Dương", meaning: "Ngứa", example: "蚊に刺されて首がかゆい。" },
  { id: 271, unit: "Unit 3", part: "Part 1", kanji: "おとなしい", kana: "おとなしい", romaji: "otonashii", hanviet: "", meaning: "Hiền lành, trầm lặng", example: "彼はおとなしい人だ。" },
  { id: 272, unit: "Unit 3", part: "Part 1", kanji: "我慢強い", kana: "がまんづよい", romaji: "gamanzuyoi", hanviet: "Ngã Mạn Cường", meaning: "Kiên trì, nhẫn nại", example: "我慢強い性格。" },
  { id: 273, unit: "Unit 3", part: "Part 1", kanji: "正直な", kana: "しょうじきな", romaji: "shoujikina", hanviet: "Chính Trực", meaning: "Thành thật", example: "彼は正直な人だから、うそをつくことができない。" },
  { id: 274, unit: "Unit 3", part: "Part 1", kanji: "けちな", kana: "けちな", romaji: "kechina", hanviet: "", meaning: "Keo kiệt", example: "あの人はとてもけchida。" },
  { id: 275, unit: "Unit 3", part: "Part 1", kanji: "わがままな", kana: "わがままな", romaji: "wagamamana", hanviet: "", meaning: "Ích kỷ, bướng bỉnh", example: "わがままな人。" },
  { id: 276, unit: "Unit 3", part: "Part 1", kanji: "積極的な", kana: "ぜっきょくてきな", romaji: "sekkyokutekina", hanviet: "Tích Cực Đích", meaning: "Tích cực", example: "積極的な人。" },
  { id: 277, unit: "Unit 3", part: "Part 1", kanji: "消極的な", kana: "しょうきょくてきな", romaji: "shoukyokutekina", hanviet: "Tiêu Cực Đích", meaning: "Tiêu cực", example: "消極的な人。" },
  { id: 278, unit: "Unit 3", part: "Part 1", kanji: "満足な", kana: "まんぞくな", romaji: "manzokuna", hanviet: "Mãn Túc", meaning: "Thỏa mãn, hài lòng", example: "アルバイトだけでは満足な収入は得られない。" },

  { id: 279, unit: "Unit 3", part: "Part 2", kanji: "不満な", kana: "ふまんな", romaji: "fumanna", hanviet: "Bất Mãn", meaning: "Bất mãn, không hài lòng", example: "この仕事に不満な点はない。" },
  { id: 280, unit: "Unit 3", part: "Part 2", kanji: "不安な", kana: "ふあんな", romaji: "fuanna", hanviet: "Bất An", meaning: "Bất an, lo lắng", example: "最近、体の調子がよくない。悪い病기ではないかと不安だ。" },
  { id: 281, unit: "Unit 3", part: "Part 2", kanji: "大変な", kana: "たいへんな", romaji: "taihenna", hanviet: "Đại Biến", meaning: "Vất vả, vất vả cực nhọc", example: "子育て trung のお母さんは大変だ。" },
  { id: 282, unit: "Unit 3", part: "Part 2", kanji: "無理な", kana: "むりな", romaji: "murina", hanviet: "Vô Lý", meaning: "Vô lý, quá sức", example: "たった100万円で家を建てるなんて無理な話だ。" },
  { id: 283, unit: "Unit 3", part: "Part 2", kanji: "不注意な", kana: "ふちゅういな", romaji: "fuchuuyina", hanviet: "Bất Chú Ý", meaning: "Không chú ý, bất cẩn", example: "不注意な人。" },
  { id: 284, unit: "Unit 3", part: "Part 2", kanji: "楽な", kana: "らくな", romaji: "rakuna", hanviet: "Lạc", meaning: "Thoải mái, nhàn nhã", example: "もう少し楽な暮らしがしたい。" },
  { id: 285, unit: "Unit 3", part: "Part 2", kanji: "面倒な", kana: "めんどうな", romaji: "mendouna", hanviet: "Diện Đảo", meaning: "Phiền hà, rắc rối", example: "ご入会にめんどうな手続きはいりません。" },
  { id: 286, unit: "Unit 3", part: "Part 2", kanji: "失礼な", kana: "しつれいな", romaji: "shitsureina", hanviet: "Thất Lễ", meaning: "Thất lễ, vô phép", example: "aいさつしても返事もしない。なんて失礼な人だろう。" },
  { id: 287, unit: "Unit 3", part: "Part 2", kanji: "当然な", kana: "とうぜんな", romaji: "touzenna", hanviet: "Đương Nhiên", meaning: "Đương nhiên, tất nhiên", example: "お金を借りたら、返すのが当然だ。" },
  { id: 288, unit: "Unit 3", part: "Part 2", kanji: "意外な", kana: "いがいな", romaji: "igaina", hanviet: "Ý Ngoại", meaning: "Ngoài dự tính, bất ngờ", example: "事故を調査するうちに意外な事実がわかった。" },
  { id: 289, unit: "Unit 3", part: "Part 2", kanji: "結構な", kana: "けっけうな", romaji: "kekkouna", hanviet: "Kết Cấu", meaning: "Tốt, ổn, tuyệt", example: "お味はいかがですか。大変結構です。" },
  { id: 290, unit: "Unit 3", part: "Part 2", kanji: "派手な", kana: "はでな", romaji: "hadena", hanviet: "Phái Thủ", meaning: "Lòe loẹt, sặc sỡ", example: "はdeな性格。" },
  { id: 291, unit: "Unit 3", part: "Part 2", kanji: "地味な", kana: "じみな", romaji: "jimina", hanviet: "Địa Vị", meaning: "Giản dị, đơn sơ", example: "じmiな性格。" },
  { id: 292, unit: "Unit 3", part: "Part 2", kanji: "おしゃれな", kana: "おしゃれな", romaji: "osharena", hanviet: "", meaning: "Sang trọng, thời thượng", example: "彼女はとてもおしゃれだ。" },
  { id: 293, unit: "Unit 3", part: "Part 2", kanji: "変な", kana: "へんな", romaji: "henna", hanviet: "Biến", meaning: "Lạ, kỳ lạ", example: "変なメールが届いたのですぐに消した。" },
  { id: 294, unit: "Unit 3", part: "Part 2", kanji: "不思議な", kana: "ふしぎな", romaji: "fushigina", hanviet: "Bất Tư Nghị", meaning: "Kỳ lạ, huyền bí", example: "この village には不思議な話が伝わっている。" },
  { id: 295, unit: "Unit 3", part: "Part 2", kanji: "ましな", kana: "ましな", romaji: "mashina", hanviet: "", meaning: "Đỡ hơn, tốt hơn", example: "せきがひどかったが、うがいをしたら前よりましになった。" },
  { id: 296, unit: "Unit 3", part: "Part 2", kanji: "むだな", kana: "むだな", romaji: "mudana", hanviet: "", meaning: "Lãng phí, vô ích", example: "落ちるとわかっているのに試験を受けるのは、むだなことだ。" },
  { id: 297, unit: "Unit 3", part: "Part 2", kanji: "自由な", kana: "じゆうな", romaji: "jiyuuna", hanviet: "Tự Do", meaning: "Tự do", example: "赤ちゃんがいるので、自由な時間がほとんどない。" },
  { id: 298, unit: "Unit 3", part: "Part 2", kanji: "不自由な", kana: "ふじゆうな", romaji: "fujiyuuna", hanviet: "Bất Tự Do", meaning: "Tàn tật, bất tiện", example: "目が不自由な人。" }
];