const vocabularyData = [
  { id: 1, unit: "Unit 1", part: "Unit 1", kanji: "男性", kana: "だんせい", romaji: "dansei", hanviet: "Nam Tính", nghia: "Nam giới", vidu: "理想の男性と結婚する。" },
  { id: 2, unit: "Unit 1", part: "Unit 1", kanji: "女性", kana: "じょせい", romaji: "josei", hanviet: "Nữ Tính", nghia: "Nữ giới", vidu: "「あの女性はだれですか」" },
  { id: 3, unit: "Unit 1", part: "Unit 1", kanji: "高齢", kana: "こうれい", romaji: "kourei", hanviet: "Cao Linh", nghia: "Cao tuổi", vidu: "祖母は高齢だが、まだとても元気だ。" },
  { id: 4, unit: "Unit 1", part: "Unit 1", kanji: "年上", kana: "としうえ", romaji: "toshiue", hanviet: "Niên Thượng", nghia: "Lớn tuổi hơn", vidu: "彼女は私より三つ年上だ。" },
  { id: 5, unit: "Unit 1", part: "Unit 1", kanji: "目上", kana: "めうえ", romaji: "meue", hanviet: "Mục Thượng", nghia: "Cấp trên, bề trên", vidu: "目上の人には敬語で話したほうがいい。" },
  { id: 6, unit: "Unit 1", part: "Unit 1", kanji: "先輩", kana: "せんぱい", romaji: "senpai", hanviet: "Tiền Bối", nghia: "Tiền bối", vidu: "職場では彼のほうが先輩だ。" },
  { id: 7, unit: "Unit 1", part: "Unit 1", kanji: "後輩", kana: "こうはい", romaji: "kouhai", hanviet: "Hậu Bối", nghia: "Hậu bối", vidu: "田中さんと私は同じ年だが、職場では彼のほうが先輩で、私は後輩だ。" },
  { id: 8, unit: "Unit 1", part: "Unit 1", kanji: "上司", kana: "じょうし", romaji: "joushi", hanviet: "Thượng Ty", nghia: "Cấp trên, sếp", vidu: "上司に相談してから決定する。" },
  { id: 9, unit: "Unit 1", part: "Unit 1", kanji: "相手", kana: "あいて", romaji: "aite", hanviet: "Tương Thủ", nghia: "Đối phương, đối thủ", vidu: "今度の試合の相手は強そうだ。" },
  { id: 10, unit: "Unit 1", part: "Unit 1", kanji: "知り合い", kana: "しりあい", romaji: "shiriai", hanviet: "Tri Hợp", nghia: "Người quen", vidu: "知り合いに息子の就職を頼む。" },
  { id: 11, unit: "Unit 1", part: "Unit 1", kanji: "友人", kana: "ゆうじん", romaji: "yuujin", hanviet: "Hữu Nhân", nghia: "Bạn bè", vidu: "「ええ、学生時代の友人です」" },
  { id: 12, unit: "Unit 1", part: "Unit 1", kanji: "仲", kana: "なか", romaji: "naka", hanviet: "Trọng", nghia: "Mối quan hệ", vidu: "私は山本さんと仲がいい。" },
  { id: 13, unit: "Unit 1", part: "Unit 1", kanji: "生年月日", kana: "せいねんがっぴ", romaji: "seinen gappi", hanviet: "Sinh Niên Nguyệt Nhật", nghia: "Ngày tháng năm sinh", vidu: "書類に生年月日を記入する。" },
  { id: 14, unit: "Unit 1", part: "Unit 1", kanji: "誕生", kana: "たんじょう", romaji: "tanjou", hanviet: "Đản Sinh", nghia: "Sự ra đời, khai sinh", vidu: "新しい命の誕生を祝う。" },
  { id: 15, unit: "Unit 1", part: "Unit 1", kanji: "年", kana: "とし", romaji: "toshi", hanviet: "Niên", nghia: "Năm, tuổi", vidu: "年の初めに1年の計画を立てる。" },
  { id: 16, unit: "Unit 1", part: "Unit 1", kanji: "出身", kana: "しゅっしん", romaji: "shusshin", hanviet: "Xuất Thân", nghia: "Xuất thân, quê quán", vidu: "私は東京の出身です。" },
  { id: 17, unit: "Unit 1", part: "Unit 1", kanji: "故郷", kana: "こきょう", romaji: "kokyou", hanviet: "Cố Hương", nghia: "Cố hương, quê nhà", vidu: "もう何年も故郷に帰っていない。" },
  { id: 18, unit: "Unit 1", part: "Unit 1", kanji: "成長", kana: "せいちょう", romaji: "seichou", hanviet: "Thành Trưởng", nghia: "Trưởng thành, phát triển", vidu: "子どもの成長を喜ぶ。" },
  { id: 19, unit: "Unit 1", part: "Unit 1", kanji: "成人", kana: "せいじん", romaji: "seijin", hanviet: "Thành Nhân", nghia: "Người trưởng thành", vidu: "日本では二十歳以上の人を成人という。" },
  { id: 20, unit: "Unit 1", part: "Unit 1", kanji: "合格", kana: "ごうかく", romaji: "gougaku", hanviet: "Hợp Cách", nghia: "Đỗ, trúng tuyển", vidu: "入学試験に合格する。" },
  { id: 21, unit: "Unit 1", part: "Unit 1", kanji: "進学", kana: "しんがく", romaji: "shingaku", hanviet: "Tiến Học", nghia: "Học lên cao hơn", vidu: "子どもの進学について考える。" },
  { id: 22, unit: "Unit 1", part: "Unit 1", kanji: "退学", kana: "たいがく", romaji: "taigaku", hanviet: "Thoái Học", nghia: "Thôi học, bỏ học", vidu: "病気で大学を退学した。" },
  { id: 23, unit: "Unit 1", part: "Unit 1", kanji: "就職", kana: "しゅうしょく", romaji: "shuushoku", hanviet: "Tựu Chức", nghia: "Có việc làm", vidu: "旅行会社に就職する。" },
  { id: 24, unit: "Unit 1", part: "Unit 1", kanji: "退職", kana: "たいしょく", romaji: "taishoku", hanviet: "Thoái Chức", nghia: "Nghỉ việc, thôi việc", vidu: "長年勤めた会社を退職した。" },
  { id: 25, unit: "Unit 1", part: "Unit 1", kanji: "失業", kana: "しつぎょう", romaji: "shitsugyou", hanviet: "Thất Nghiệp", nghia: "Thất nghiệp, mất việc", vidu: "会社が倒産して失業した。" },
  { id: 26, unit: "Unit 1", part: "Unit 1", kanji: "残業", kana: "ざんぎょう", romaji: "zangyou", hanviet: "Tàn Nghiệp", nghia: "Làm thêm giờ", vidu: "残業が多くて疲れた。" },
  { id: 27, unit: "Unit 1", part: "Unit 1", kanji: "生活", kana: "せいかつ", romaji: "seikatsu", hanviet: "Sinh Hoạt", nghia: "Cuộc sống, sinh hoạt", vidu: "健康的な生活を送る。" },
  { id: 28, unit: "Unit 1", part: "Unit 1", kanji: "通勤", kana: "つうきん", romaji: "tsukin", hanviet: "Thông Cần", nghia: "Đi làm", vidu: "私は毎日1時間かけて通勤している。" },
  { id: 29, unit: "Unit 1", part: "Unit 1", kanji: "学歴", kana: "がくれき", romaji: "gakureki", hanviet: "Học Lịch", nghia: "Học vấn, bằng cấp", vidu: "学歴が高くても、実力があるかはわからない。" },
  { id: 30, unit: "Unit 1", part: "Unit 1", kanji: "給料", kana: "きゅうりょう", romaji: "kyuuryou", hanviet: "Cấp Liệu", nghia: "Tiền lương", vidu: "会社から給料をもらう。" },
  { id: 31, unit: "Unit 1", part: "Unit 1", kanji: "面接", kana: "めんせつ", romaji: "mensetsu", hanviet: "Diện Tiếp", nghia: "Phỏng vấn", vidu: "きょう、会社の人との面接がある。" },
  { id: 32, unit: "Unit 1", part: "Unit 1", kanji: "休憩", kana: "きゅうけい", romaji: "kyuukei", hanviet: "Hưu Khế", nghia: "Nghỉ giải lao", vidu: "「ではここで、10分間の休憩です」" },
  { id: 33, unit: "Unit 1", part: "Unit 1", kanji: "観光", kana: "かんこう", romaji: "kankou", hanviet: "Quan Quang", nghia: "Tham quan, du lịch", vidu: "来日の目的は観光です。" },
  { id: 34, unit: "Unit 1", part: "Unit 1", kanji: "帰国", kana: "きこく", romaji: "kikoku", hanviet: "Quy Quốc", nghia: "Về nước", vidu: "今度の正月には帰国するつもりだ。" },
  { id: 35, unit: "Unit 1", part: "Unit 1", kanji: "帰省", kana: "きせい", romaji: "kisei", hanviet: "Quy Tỉnh", nghia: "Về quê thăm nhà", vidu: "お盆にはふるさとに帰省する日本人が多い。" },
  { id: 36, unit: "Unit 1", part: "Unit 1", kanji: "帰宅", kana: "きたく", romaji: "kitaku", hanviet: "Quy Trạch", nghia: "Về nhà (hàng ngày)", vidu: "毎日忙しくて帰宅が遅い。" },
  { id: 37, unit: "Unit 1", part: "Unit 1", kanji: "参加", kana: "さんか", romaji: "sanka", hanviet: "Tham Gia", nghia: "Tham gia", vidu: "ボランティア活動に参加する。" },
  { id: 38, unit: "Unit 1", part: "Unit 1", kanji: "出席", kana: "しゅっせき", romaji: "shusseki", hanviet: "Xuất Tịch", nghia: "Có mặt, hiện diện", vidu: "ミーティングに出席する。" },
  { id: 39, unit: "Unit 1", part: "Unit 1", kanji: "欠席", kana: "けっせき", romaji: "kesseki", hanviet: "Khiếm Tịch", nghia: "Vắng mặt, nghỉ học", vidu: "授業を欠席する。" },
  { id: 40, unit: "Unit 1", part: "Unit 1", kanji: "遅刻", kana: "ちこく", romaji: "chikoku", hanviet: "Trì Khắc", nghia: "Đến muộn, trễ", vidu: "寝坊して授業に遅刻する。" },
  { id: 41, unit: "Unit 1", part: "Unit 1", kanji: "化粧", kana: "けしょう", romaji: "keshou", hanviet: "Hóa Trang", nghia: "Trang điểm", vidu: "「あなたは毎日、お化粧に何分ぐらいかけていますか」" },
  { id: 42, unit: "Unit 1", part: "Unit 1", kanji: "计算", kana: "けいさん", romaji: "keisan", hanviet: "Kế Toán", nghia: "Tính toán", vidu: "私は計算が苦手だ。" },
  { id: 43, unit: "Unit 1", part: "Unit 1", kanji: "計画", kana: "けいかく", romaji: "keikaku", hanviet: "Kế Họa", nghia: "Kế hoạch", vidu: "来年の計画を立てる。" },
  { id: 44, unit: "Unit 1", part: "Unit 1", kanji: "成功", kana: "せいこう", romaji: "seikou", hanviet: "Thành Công", nghia: "Thành công", vidu: "実験に成功する。" },
  { id: 45, unit: "Unit 1", part: "Unit 1", kanji: "失敗", kana: "しっぱい", romaji: "shippai", hanviet: "Thất Bại", nghia: "Thất bại", vidu: "実験の失敗で、計画は中止になった。" },
  { id: 46, unit: "Unit 1", part: "Unit 1", kanji: "準備", kana: "じゅんび", romaji: "junbi", hanviet: "Chuẩn Bị", nghia: "Chuẩn bị", vidu: "引っ越しの準備が終わった。" },
  { id: 47, unit: "Unit 1", part: "Unit 1", kanji: "整理", kana: "せいり", romaji: "seiri", hanviet: "Chỉnh Lý", nghia: "Sắp xếp, thu dọn", vidu: "資料の整理。" },
  { id: 48, unit: "Unit 1", part: "Unit 1", kanji: "注文", kana: "ちゅうもん", romaji: "chuumon", hanviet: "Chú Văn", nghia: "Đặt hàng, gọi món", vidu: "喫茶店でコーヒーを注文する。" },
  { id: 49, unit: "Unit 1", part: "Unit 1", kanji: "貯金", kana: "ちょきん", romaji: "chokin", hanviet: "Trữ Kim", nghia: "Tiền tiết kiệm", vidu: "銀行にボーナスを貯金する。" },
  { id: 50, unit: "Unit 1", part: "Unit 1", kanji: "徹夜", kana: "てつや", romaji: "tetsuya", hanviet: "Triệt Dạ", nghia: "Thức suốt đêm", vidu: "徹夜で勉強する。" },
  { id: 51, unit: "Unit 1", part: "Unit 1", kanji: "引っ越し", kana: "ひっこし", romaji: "hikkoshi", hanviet: "Dẫn Việt", nghia: "Chuyển nhà", vidu: "引っ越しを手伝う。" },
  { id: 52, unit: "Unit 1", part: "Unit 1", kanji: "身長", kana: "しんちょう", romaji: "shinchou", hanviet: "Thân Trường", nghia: "Chiều cao", vidu: "身長を測る。" },
  { id: 53, unit: "Unit 1", part: "Unit 1", kanji: "体重", kana: "たいじゅう", romaji: "taijuu", hanviet: "Thể Trọng", nghia: "Cân nặng", vidu: "体重を量る。" },
  { id: 54, unit: "Unit 1", part: "Unit 1", kanji: "けが", kana: "kega", romaji: "kega", hanviet: "", nghia: "Vết thương", vidu: "転んで足にけがをした。" },
  { id: 55, unit: "Unit 1", part: "Unit 1", kanji: "会", kana: "かい", romaji: "kai", hanviet: "Hội", nghia: "Tiệc, buổi lễ", vidu: "忘年会を開く。" },
  { id: 56, unit: "Unit 1", part: "Unit 1", kanji: "趣味", kana: "しゅみ", romaji: "shumi", hanviet: "Thú Vị", nghia: "Sở thích", vidu: "趣味は読書です。" },
  { id: 57, unit: "Unit 1", part: "Unit 1", kanji: "興味", kana: "きょうみ", romaji: "kyoumi", hanviet: "Hưng Vị", nghia: "Hứng thú", vidu: "私は歴史に興味がある。" },
  { id: 58, unit: "Unit 1", part: "Unit 1", kanji: "思い出", kana: "おもいで", romaji: "omoide", hanviet: "Tư Xuất", nghia: "Kỷ niệm", vidu: "子供のころの楽しい思い出。" },
  { id: 59, unit: "Unit 1", part: "Unit 1", kanji: "冗談", kana: "じょうだん", romaji: "joudan", hanviet: "Nhũng Đàm", nghia: "Nói đùa", vidu: "冗談を言ったら、みんなが本気にした。" },
  { id: 60, unit: "Unit 1", part: "Unit 1", kanji: "目的", kana: "もくてき", romaji: "mokuteki", hanviet: "Mục Đích", nghia: "Mục đích", vidu: "日本に来た目的は大学への入学だ。" },
  { id: 61, unit: "Unit 1", part: "Unit 1", kanji: "約束", kana: "やくそく", romaji: "yakusoku", hanviet: "Ước Thúc", nghia: "Lời hứa, cuộc hẹn", vidu: "彼と結婚の約束をした。" },
  { id: 62, unit: "Unit 1", part: "Unit 1", kanji: "おしゃべり", kana: "oshaberi", romaji: "oshaberi", hanviet: "", nghia: "Nói chuyện, tán gẫu", vidu: "授業中におしゃべりして、先生に怒られた。" },
  { id: 63, unit: "Unit 1", part: "Unit 1", kanji: "遠慮", kana: "えんりょ", romaji: "enryo", hanviet: "Viễn Lự", nghia: "Ngại ngùng, giữ kẽ", vidu: "「遠慮しないで食べてください」" },
  { id: 64, unit: "Unit 1", part: "Unit 1", kanji: "我慢", kana: "がまん", romaji: "gaman", hanviet: "Ngã Mạn", nghia: "Chịu đựng, nhẫn nại", vidu: "痛くてもがまんする。" },
  { id: 65, unit: "Unit 1", part: "Unit 1", kanji: "迷惑", kana: "めいわく", romaji: "meiwaku", hanviet: "Mê Hoặc", nghia: "Làm phiền, quấy rầy", vidu: "人に迷惑をかけてはいけない。" },
  { id: 66, unit: "Unit 1", part: "Unit 1", kanji: "希望", kana: "きぼう", romaji: "kibou", hanviet: "Hy Vọng", nghia: "Hy vọng, ý muốn", vidu: "最後まで希望を捨ててはいけない。" },
  { id: 67, unit: "Unit 1", part: "Unit 1", kanji: "夢", kana: "ゆめ", romaji: "yume", hanviet: "Mộng", nghia: "Giấc mơ, ước mơ", vidu: "きのう、こわい夢を見た。" },
  { id: 68, unit: "Unit 1", part: "Unit 1", kanji: "賛成", kana: "さんせい", romaji: "sansei", hanviet: "Tán Thành", nghia: "Tán thành, đồng ý", vidu: "「賛成の人は手を挙げてください」" },
  { id: 69, unit: "Unit 1", part: "Unit 1", kanji: "反対", kana: "はんたい", romaji: "hantai", hanviet: "Phản Đối", nghia: "Phản đối, ngược lại", vidu: "彼の意見には反対だ。" },
  { id: 70, unit: "Unit 1", part: "Unit 1", kanji: "想像", kana: "そうぞう", romaji: "souzou", hanviet: "Tưởng Tượng", nghia: "Tưởng tượng", vidu: "想像と現実は違う。" },
  { id: 71, unit: "Unit 1", part: "Unit 1", kanji: "努力", kana: "どりょく", romaji: "doryoku", hanviet: "Nỗ Lực", nghia: "Nỗ lực, cố gắng", vidu: "一生懸命、努力をする。" },
  { id: 72, unit: "Unit 1", part: "Unit 1", kanji: "太陽", kana: "たいよう", romaji: "taiyou", hanviet: "Thái Dương", nghia: "Mặt trời", vidu: "太陽が昇って、暖かくなった。" },
  { id: 73, unit: "Unit 1", part: "Unit 1", kanji: "地球", kana: "ちきゅう", romaji: "chikyuu", hanviet: "Địa Cầu", nghia: "Trái đất", vidu: "地球の環境が悪化している。" },
  { id: 74, unit: "Unit 1", part: "Unit 1", kanji: "温度", kana: "おんど", romaji: "ondo", hanviet: "Ôn Độ", nghia: "Nhiệt độ", vidu: "温度を測る。" },
  { id: 75, unit: "Unit 1", part: "Unit 1", kanji: "湿度", kana: "しつど", romaji: "shitsudo", hanviet: "Thấp Độ", nghia: "Độ ẩm", vidu: "今年の夏は特に湿度が高い。" },
  { id: 76, unit: "Unit 1", part: "Unit 1", kanji: "湿気", kana: "しっけ", romaji: "shikke", hanviet: "Thấp Khí", nghia: "Hơi ẩm", vidu: "日本の夏は湿気が多い。" },
  { id: 77, unit: "Unit 1", part: "Unit 1", kanji: "梅雨", kana: "つゆ", romaji: "tsuyu", hanviet: "Mai Vũ", nghia: "Mùa mưa", vidu: "6月から7月は梅雨の時期だ。" },
  { id: 78, unit: "Unit 1", part: "Unit 1", kanji: "かび", kana: "kabi", romaji: "kabi", hanviet: "", nghia: "Nấm mốc", vidu: "梅雨の時期はかびがはえやすい。" },
  { id: 79, unit: "Unit 1", part: "Unit 1", kanji: "暖房", kana: "だんぼう", romaji: "danbou", hanviet: "Noãn Phòng", nghia: "Lò sưởi, hệ thống sưởi", vidu: "寒いので暖房をつける。" },
  { id: 80, unit: "Unit 1", part: "Unit 1", kanji: "皮", kana: "かわ", romaji: "kawa", hanviet: "Bì", nghia: "Da, vỏ", vidu: "りんごの皮をむいて食べる。" },
  { id: 81, unit: "Unit 1", part: "Unit 1", kanji: "缶", kana: "かん", romaji: "kan", hanviet: "Phẫu", nghia: "Lon, hộp thiếc", vidu: "おかしをカンに入れて保存する。" },
  { id: 82, unit: "Unit 1", part: "Unit 1", kanji: "画面", kana: "がめん", romaji: "gamen", hanviet: "Họa Diện", nghia: "Màn hình", vidu: "パソコンの画面をずっと見ていると、目が疲れる。" },
  { id: 83, unit: "Unit 1", part: "Unit 1", kanji: "番組", kana: "ばんぐみ", romaji: "bangumi", hanviet: "Phiên Tổ", nghia: "Chương trình (TV, radio)", vidu: "テレビの番組を見る。" },
  { id: 84, unit: "Unit 1", part: "Unit 1", kanji: "記事", kana: "きじ", romaji: "kiji", hanviet: "Ký Sự", nghia: "Bài báo, tin tức", vidu: "この記事によると、日本に住む外国人が増えているそうだ。" },
  { id: 85, unit: "Unit 1", part: "Unit 1", kanji: "近所", kana: "きんじょ", romaji: "kinjo", hanviet: "Cận Sở", nghia: "Hàng xóm, vùng lân cận", vidu: "近所の人とは仲良くしたほうがいい。" },
  { id: 86, unit: "Unit 1", part: "Unit 1", kanji: "警察", kana: "けいさつ", romaji: "keisatsu", hanviet: "Cảnh Sát", nghia: "Cảnh sát", vidu: "自転車を盗まれたので、警察に届けた。" },
  { id: 87, unit: "Unit 1", part: "Unit 1", kanji: "犯人", kana: "はんにん", romaji: "hannin", hanviet: "Phạm Nhân", nghia: "Thủ phạm, phạm nhân", vidu: "事件の犯人をつかまえる。" },
  { id: 88, unit: "Unit 1", part: "Unit 1", kanji: "小銭", kana: "こぜに", romaji: "kozeni", hanviet: "Tiểu Tiền", nghia: "Tiền lẻ", vidu: "バスに乗ってから小銭がないことに気がつき、とても困った。" },
  { id: 89, unit: "Unit 1", part: "Unit 1", kanji: "ごちそう", kana: "gochisou", romaji: "gochisou", hanviet: "", nghia: "Tiệc chiêu đãi, món ngon", vidu: "家族みんなでごちそうを食べて、祖父の誕生日を祝った。" },
  { id: 90, unit: "Unit 1", part: "Unit 1", kanji: "作者", kana: "さくしゃ", romaji: "sakusha", hanviet: "Tác Giả", nghia: "Tác giả", vidu: "「ハムレット」の作者はシェイクスピアです。" },
  { id: 91, unit: "Unit 1", part: "Unit 1", kanji: "作品", kana: "さくひん", romaji: "sakuhin", hanviet: "Tác Phẩm", nghia: "Tác phẩm", vidu: "学生の作品をロビーに展示する。" },
  { id: 92, unit: "Unit 1", part: "Unit 1", kanji: "制服", kana: "せいふく", romaji: "seifuku", hanviet: "Chế Phục", nghia: "Đồng phục", vidu: "日本の中学校には制服のある学校が多い。" },
  { id: 93, unit: "Unit 1", part: "Unit 1", kanji: "洗剤", kana: "せんざい", romaji: "senzai", hanviet: "Tẩy Tễ", nghia: "Chất tẩy rửa", vidu: "洗剤で食器を洗う。" },
  { id: 94, unit: "Unit 1", part: "Unit 1", kanji: "底", kana: "そこ", romaji: "soko", hanviet: "Để", nghia: "Đáy", vidu: "くつの底に穴があく。" },
  { id: 95, unit: "Unit 1", part: "Unit 1", kanji: "地下", kana: "ちか", romaji: "chika", hanviet: "Địa Hạ", nghia: "Tầng hầm, dưới đất", vidu: "大都市は地下の開発が進んでいる。" },
  { id: 96, unit: "Unit 1", part: "Unit 1", kanji: "寺", kana: "てら", romaji: "tera", hanviet: "Tự", nghia: "Chùa", vidu: "寺にまいりする。" },
  { id: 97, unit: "Unit 1", part: "Unit 1", kanji: "道路", kana: "どうろ", romaji: "douro", hanviet: "Đạo Lộ", nghia: "Con đường", vidu: "道路が込む。" },
  { id: 98, unit: "Unit 1", part: "Unit 1", kanji: "坂", kana: "さか", romaji: "saka", hanviet: "Phản", nghia: "Dốc", vidu: "坂を上る。" },
  { id: 99, unit: "Unit 1", part: "Unit 1", kanji: "煙", kana: "けむり", romaji: "kemuri", hanviet: "Yên", nghia: "Khói", vidu: "「火事のときは、煙に注意して逃げてください」" },
  { id: 100, unit: "Unit 1", part: "Unit 1", kanji: "灰", kana: "はい", romaji: "hai", hanviet: "Hôi", nghia: "Tro", vidu: "紙が燃えて灰になる。" },
  { id: 101, unit: "Unit 1", part: "Unit 1", kanji: "判", kana: "はん", romaji: "han", hanviet: "Phán", nghia: "Con dấu", vidu: "書類に判を押す。" },
  { id: 102, unit: "Unit 1", part: "Unit 1", kanji: "名刺", kana: "めいし", romaji: "meishi", hanviet: "Danh Thứ", nghia: "Danh thiếp", vidu: "名刺を交換する。" },
  { id: 103, unit: "Unit 1", part: "Unit 1", kanji: "免許", kana: "めんきょ", romaji: "menkyo", hanviet: "Miễn Hứa", nghia: "Giấy phép", vidu: "レストランを開くには、調理師の免許が必要だ。" },
  { id: 104, unit: "Unit 1", part: "Unit 1", kanji: "多く", kana: "おおく", romaji: "ooku", hanviet: "Đa", nghia: "Nhiều", vidu: "オリンピックには多くの国が参加した。" },
  { id: 105, unit: "Unit 1", part: "Unit 1", kanji: "前半", kana: "ぜんはん", romaji: "zenhan", hanviet: "Tiền Bán", nghia: "Nửa đầu", vidu: "映画の前半はたいくつだったが、後半はおもしろかった。" },
  { id: 106, unit: "Unit 1", part: "Unit 1", kanji: "後半", kana: "こうはん", romaji: "kouhan", hanviet: "Hậu Bán", nghia: "Nửa sau", vidu: "映画の前半はたいくつだったが、後半はおもしろかった。" },
  { id: 107, unit: "Unit 1", part: "Unit 1", kanji: "最高", kana: "さいこう", romaji: "saikou", hanviet: "Tối Cao", nghia: "Cao nhất, tuyệt nhất", vidu: "今日は今までの人生で最高の日だ。" },
  { id: 108, unit: "Unit 1", part: "Unit 1", kanji: "最低", kana: "さいてい", romaji: "saitei", hanviet: "Tối Đê", nghia: "Thấp nhất, tồi nhất", vidu: "クラスで最低の点をとってしまった。" },
  { id: 109, unit: "Unit 1", part: "Unit 1", kanji: "最初", kana: "さいしょ", romaji: "saisho", hanviet: "Tối Sơ", nghia: "Đầu tiên", vidu: "最初にひらがなを、次にカタカナを勉強した。" },
  { id: 110, unit: "Unit 1", part: "Unit 1", kanji: "最后", kana: "さいご", romaji: "saigo", hanviet: "Tối Hậu", nghia: "Cuối cùng", vidu: "日本に来たばかりのころ、最初は何もわからなかった。" },
  { id: 111, unit: "Unit 1", part: "Unit 1", kanji: "自動", kana: "じどう", romaji: "jidou", hanviet: "Tự Động", nghia: "Tự động", vidu: "このドアは自動だから、手で開けなくてもいい。" },
  { id: 112, unit: "Unit 1", part: "Unit 1", kanji: "種類", kana: "しゅゅるい", romaji: "shurui", hanviet: "Chủng Loại", nghia: "Loại, chủng loại", vidu: "公園にはいろいろな種類の花がある。" },
  { id: 113, unit: "Unit 1", part: "Unit 1", kanji: "性格", kana: "せいかく", romaji: "seikaku", hanviet: "Tính Cách", nghia: "Tính cách", vidu: "あの人は性格がいいので、みんなに好かれている。" },
  { id: 114, unit: "Unit 1", part: "Unit 1", kanji: "性質", kana: "せいしつ", romaji: "seishitsu", hanviet: "Tính Chất", nghia: "Tính chất, đặc tính", vidu: "この布は燃えにくい性質を持っている。" },
  { id: 115, unit: "Unit 1", part: "Unit 1", kanji: "順番", kana: "じゅんばん", romaji: "junban", hanviet: "Thuận Phiên", nghia: "Thứ tự, lần lượt", vidu: "発表の順番を決める。" },
  { id: 116, unit: "Unit 1", part: "Unit 1", kanji: "番", kana: "ばん", romaji: "ban", hanviet: "Phiên", nghia: "Lượt", vidu: "次は私の番だ。" },
  { id: 117, unit: "Unit 1", part: "Unit 1", kanji: "方法", kana: "ほうほう", romaji: "houhou", hanviet: "Phương Pháp", nghia: "Phương pháp, cách thức", vidu: "いい方法を探す。" },
  { id: 118, unit: "Unit 1", part: "Unit 1", kanji: "製品", kana: "せいひん", romaji: "seihin", hanviet: "Chế Phẩm", nghia: "Sản phẩm, hàng hóa", vidu: "完成した製品を検査する。" },
  { id: 119, unit: "Unit 1", part: "Unit 1", kanji: "値上がり", kana: "ねあがり", romaji: "neagari", hanviet: "Trị Thượng", nghia: "Tăng giá", vidu: "食品の値上がり。" },
  { id: 120, unit: "Unit 1", part: "Unit 1", kanji: "生", kana: "生", romaji: "nama", hanviet: "Sinh", nghia: "Tươi sống", vidu: "生の魚。" },
  { id: 121, unit: "Unit 2", part: "Unit 2", kanji: "渇く", kana: "かわく", romaji: "kawaku", hanviet: "Khát", nghia: "Khát", vidu: "のどがかわいた。" },
  { id: 122, unit: "Unit 2", part: "Unit 2", kanji: "嗅ぐ", kana: "かぐ", romaji: "kagu", hanviet: "Khứu", nghia: "Ngửi", vidu: "においをかぐ。" },
  { id: 123, unit: "Unit 2", part: "Unit 2", kanji: "叩く", kana: "たたく", romaji: "tataku", hanviet: "Khấu", nghia: "Vỗ, đánh, gõ", vidu: "子供のおしりをたたく。" },
  { id: 124, unit: "Unit 2", part: "Unit 2", kanji: "殴る", kana: "なぐる", romaji: "naguru", hanviet: "Ẩu", nghia: "Đấm", vidu: "教師が生徒をなぐって、問題になっている。" },
  { id: 125, unit: "Unit 2", part: "Unit 2", kanji: "蹴る", kana: "ける", romaji: "keru", hanviet: "Xúc", nghia: "Đá", vidu: "ボールをける。" },
  { id: 126, unit: "Unit 2", part: "Unit 2", kanji: "抱く", kana: "だく", romaji: "daku", hanviet: "Bão", nghia: "Ôm", vidu: "子供を両手でしっかりと抱く。" },
  { id: 127, unit: "Unit 2", part: "Unit 2", kanji: "倒れる", kana: "たおれる", romaji: "taoreru", hanviet: "Đảo", nghia: "Đổ, ngã", vidu: "台風で木が倒れた。" },
  { id: 128, unit: "Unit 2", part: "Unit 2", kanji: "倒す", kana: "たおす", romaji: "taosu", hanviet: "Đảo", nghia: "Làm đổ, đánh bại", vidu: "花びんを倒して割ってしまった。" },
  { id: 129, unit: "Unit 2", part: "Unit 2", kanji: "起きる", kana: "おきる", romaji: "okiru", hanviet: "Khởi", nghia: "Thức dậy, xảy ra", vidu: "きょうは8時に起きた。" },
  { id: 130, unit: "Unit 2", part: "Unit 2", kanji: "起こす", kana: "おこす", romaji: "okosuu", hanviet: "Khởi", nghia: "Đánh thức, gây ra", vidu: "うちの子は朝起こしてもなかなか起きない。" },
  { id: 131, unit: "Unit 2", part: "Unit 2", kanji: "尋ねる", kana: "たずねる", romaji: "tazuneru", hanviet: "Tầm", nghia: "Hỏi", vidu: "交番で警官に市役所までの道をたずねた。" },
  { id: 132, unit: "Unit 2", part: "Unit 2", kanji: "呼ぶ", kana: "よぶ", romaji: "yobu", hanviet: "Hô", nghia: "Gọi", vidu: "「名前を呼ばれたら返事をしてください」" },
  { id: 133, unit: "Unit 2", part: "Unit 2", kanji: "叫ぶ", kana: "さけぶ", romaji: "sakebu", hanviet: "Khiếu", nghia: "Gào, hét", vidu: "大声で叫んだが、相手は気づかずに行ってしまった。" },
  { id: 134, unit: "Unit 2", part: "Unit 2", kanji: "黙る", kana: "だまる", romaji: "damaru", hanviet: "Mặc", nghia: "Im lặng", vidu: "先生が質問したが、だれも答えないでだまっている。" },
  { id: 135, unit: "Unit 2", part: "Unit 2", kanji: "飼う", kana: "かう", romaji: "kau", hanviet: "Tự", nghia: "Nuôi (thú cưng)", vidu: "何かペットを飼いたいと思っている。" },
  { id: 136, unit: "Unit 2", part: "Unit 2", kanji: "数える", kana: "かぞえる", romaji: "kazoeru", hanviet: "Số", nghia: "Đếm", vidu: "数を数える。" },
  { id: 137, unit: "Unit 2", part: "Unit 2", kanji: "乾く", kana: "かわく", romaji: "kawaku", hanviet: "Can", nghia: "Khô", vidu: "風が強かったので、外に干した洗濯物はすぐに乾いた。" },
  { id: 138, unit: "Unit 2", part: "Unit 2", kanji: "乾かす", kana: "かわかす", romaji: "kawakasu", hanviet: "Can", nghia: "Làm khô", vidu: "ドライヤーでぬれた髪を乾かした。" },
  { id: 139, unit: "Unit 2", part: "Unit 2", kanji: "畳む", kana: "たたむ", romaji: "tatamu", hanviet: "Điệp", nghia: "Gấp", vidu: "洗濯物をたたむ。" },
  { id: 140, unit: "Unit 2", part: "Unit 2", kanji: "誘う", kana: "さそう", romaji: "sasou", hanviet: "Dụ", nghia: "Mới, rủ", vidu: "友だちを誘って映画を見に行った。" },
  { id: 141, unit: "Unit 2", part: "Unit 2", kanji: "奢る", kana: "おごる", romaji: "ogoru", hanviet: "Sa", nghia: "Khao, đãi", vidu: "きのうは後輩に焼き肉をおごった。" },
  { id: 142, unit: "Unit 2", part: "Unit 2", kanji: "預かる", kana: "あずかる", romaji: "azukaru", hanviet: "Dự", nghia: "Trông nom, chăm sóc", vidu: "旅行に行く友だちから犬を預かることになった。" },
  { id: 143, unit: "Unit 2", part: "Unit 2", kanji: "預ける", kana: "あずける", romaji: "azukeru", hanviet: "Dự", nghia: "Gửi, giao phó", vidu: "銀行にお金を預けると、利子がつく。" },
  { id: 144, unit: "Unit 2", part: "Unit 2", kanji: "決まる", kana: "きまる", romaji: "kimaru", hanviet: "Quyết", nghia: "Được quyết định", vidu: "帰国の日が決まった。" },
  { id: 145, unit: "Unit 2", part: "Unit 2", kanji: "決める", kana: "きめる", romaji: "kimeru", hanviet: "Quyết", nghia: "Quyết định", vidu: "「進学か就職か、早く決めたほうがいいですよ」" },
  { id: 146, unit: "Unit 2", part: "Unit 2", kanji: "写る", kana: "うつる", romaji: "utsuru", hanviet: "Tả", nghia: "Chụp được, chiếu", vidu: "このカメラは暗いところでもよく写る。" },
  { id: 147, unit: "Unit 2", part: "Unit 2", kanji: "写す", kana: "うつす", romaji: "utsusu", hanviet: "Tả", nghia: "Chụp, sao chép", vidu: "写真を写す。" },
  { id: 148, unit: "Unit 2", part: "Unit 2", kanji: "思い出す", kana: "おもいだす", romaji: "omoidasu", hanviet: "Tư Xuất", nghia: "Nhớ lại", vidu: "毎年春になると、高校の入学式を思い出します。" },
  { id: 149, unit: "Unit 2", part: "Unit 2", kanji: "教わる", kana: "おそわる", romaji: "osowaru", hanviet: "Giáo", nghia: "Được dạy", vidu: "この料理の作り方は母に教わりました。" },
  { id: 150, unit: "Unit 2", part: "Unit 2", kanji: "申し込む", kana: "もうしこむ", romaji: "moushikomu", hanviet: "Thân Thâu", nghia: "Đăng ký", vidu: "パーティーに参加を申し込む。" },
  { id: 151, unit: "Unit 2", part: "Unit 2", kanji: "断る", kana: "ことわる", romaji: "kotowaru", hanviet: "Đoạn", nghia: "Từ chối", vidu: "頼まれた仕事を断った。" },
  { id: 152, unit: "Unit 2", part: "Unit 2", kanji: "見つかる", kana: "みつかる", romaji: "mitsukaru", hanviet: "Kiến", nghia: "Tìm thấy, bị bắt gặp", vidu: "なくなったと思っていた指輪が、ソファーの下で見つかった。" },
  { id: 153, unit: "Unit 2", part: "Unit 2", kanji: "見つける", kana: "みつける", romaji: "mitsukeru", hanviet: "Kiến", nghia: "Tìm thấy", vidu: "なくなったと思っていた指輪を、ソファーの下で見つけた。" },
  { id: 154, unit: "Unit 2", part: "Unit 2", kanji: "捕まる", kana: "つかまる", romaji: "tsukamaru", hanviet: "Bộ", nghia: "Bị bắt, nắm vào", vidu: "犯人が警察に捕まった。" },
  { id: 155, unit: "Unit 2", part: "Unit 2", kanji: "捕まえる", kana: "つかまえる", romaji: "tsukamaeru", hanviet: "Bộ", nghia: "Bắt giữ", vidu: "警察が泥棒を捕まえた。" },
  { id: 156, unit: "Unit 2", part: "Unit 2", kanji: "乗る", kana: "のる", romaji: "noru", hanviet: "Thừa", nghia: "Lên xe, cưỡi", vidu: "毎朝、電車に乗って学校に通っている。" },
  { id: 157, unit: "Unit 2", part: "Unit 2", kanji: "乗せる", kana: "のせる", romaji: "noseru", hanviet: "Thừa", nghia: "Cho lên xe, chở", vidu: "子どもを車に乗せて、学校まで送って行った。" },
  { id: 158, unit: "Unit 2", part: "Unit 2", kanji: "降りる", kana: "おりる", romaji: "oriru", hanviet: "Giáng", nghia: "Xuống xe", vidu: "電車を降りる。" },
  { id: 159, unit: "Unit 2", part: "Unit 2", kanji: "降ろす", kana: "おろす", romaji: "orosu", hanviet: "Giáng", nghia: "Cho xuống xe, rút tiền", vidu: "「あの銀行の前で降ろしてください」" },
  { id: 160, unit: "Unit 2", part: "Unit 2", kanji: "直る", kana: "なおる", romaji: "naoru", hanviet: "Trực", nghia: "Được sửa", vidu: "こわれたパソコンが直った。" },
  { id: 161, unit: "Unit 2", part: "Unit 2", kanji: "直す", kana: "なおす", romaji: "naosu", hanviet: "Trực", nghia: "Sửa chữa, dịch", vidu: "こわれた時計を直す。" },
  { id: 162, unit: "Unit 2", part: "Unit 2", kanji: "治る", kana: "なおる", romaji: "naoru", hanviet: "Trị", nghia: "Khỏi bệnh", vidu: "なかなか頭痛が治らない。" },
  { id: 163, unit: "Unit 2", part: "Unit 2", kanji: "治す", kana: "なおす", romaji: "naosu", hanviet: "Trị", nghia: "Chữa bệnh", vidu: "「よく休んで早くかぜを治してください」" },
  { id: 164, unit: "Unit 2", part: "Unit 2", kanji: "亡くなる", kana: "なくなる", romaji: "nakunaru", hanviet: "Vong", nghia: "Mất, qua đời", vidu: "社長が90歳でなくなった。" },
  { id: 165, unit: "Unit 2", part: "Unit 2", kanji: "亡くす", kana: "なくす", romaji: "nakusu", hanviet: "Vong", nghia: "Mất (người thân)", vidu: "彼は子どものとき、父親をなくした。" },
  { id: 166, unit: "Unit 2", part: "Unit 2", kanji: "生まれる", kana: "うまれる", romaji: "umareru", hanviet: "Sinh", nghia: "Được sinh ra", vidu: "先月子どもが生まれた。" },
  { id: 167, unit: "Unit 2", part: "Unit 2", kanji: "産む", kana: "うむ", romaji: "umu", hanviet: "Sán", nghia: "Sinh đẻ", vidu: "妻が先日元気な女の子を産んだ。" },
  { id: 168, unit: "Unit 2", part: "Unit 2", kanji: "出会う", kana: "であう", romaji: "deau", hanviet: "Xuất Hội", nghia: "Gặp gỡ ngẫu nhiên", vidu: "駅で偶然大学時代の友人と出会った。" },
  { id: 169, unit: "Unit 2", part: "Unit 2", kanji: "訪ねる", kana: "たずねる", romaji: "tazuneru", hanviet: "Phỏng", nghia: "Ghé thăm", vidu: "友人の家を訪ねた。" },
  { id: 170, unit: "Unit 2", part: "Unit 2", kanji: "付き合う", kana: "つきあう", romaji: "tsukiau", hanviet: "Phó Hợp", nghia: "Kết giao, hẹn hò", vidu: "隣の家の人と親しく付き合っている。" },
  { id: 171, unit: "Unit 2", part: "Unit 2", kanji: "効く", kana: "きく", romaji: "kiku", hanviet: "Hiệu", nghia: "Có hiệu quả", vidu: "この薬は頭痛によく効く。" },
  { id: 172, unit: "Unit 2", part: "Unit 2", kanji: "流行る", kana: "はやる", romaji: "hayaru", hanviet: "Lưu Hành", nghia: "Thịnh hành, lan rộng", vidu: "この冬は赤い色が流行っている。" },
  { id: 173, unit: "Unit 2", part: "Unit 2", kanji: "経つ", kana: "たつ", romaji: "tatsu", hanviet: "Kinh", nghia: "Trải qua (thời gian)", vidu: "日本へ来てから10年が経った。" },
  { id: 174, unit: "Unit 2", part: "Unit 2", kanji: "間に合う", kana: "まニアう", romaji: "maniau", hanviet: "Gian Hợp", nghia: "Kịp thời", vidu: "電車が遅れたが、なんとか授業に間に合った。" },
  { id: 175, unit: "Unit 2", part: "Unit 2", kanji: "間に合わせる", kana: "まにあわせる", romaji: "maniawaseru", hanviet: "Gian Hợp", nghia: "Làm cho kịp", vidu: "レポートを、がんばって締め切りに間に合わせた。" },
  { id: 176, unit: "Unit 2", part: "Unit 2", kanji: "通う", kana: "かよう", romaji: "kayou", hanviet: "Thông", nghia: "Đi lại thường xuyên", vidu: "学校に通う。" },
  { id: 177, unit: "Unit 2", part: "Unit 2", kanji: "込む", kana: "こむ", romaji: "komu", hanviet: "Vận", nghia: "Đông đúc", vidu: "電車が込む。" },
  { id: 178, unit: "Unit 2", part: "Unit 2", kanji: "すれ違う", kana: "すれちがう", romaji: "surechigau", hanviet: "Vi", nghia: "Đi ngang qua nhau", vidu: "この道はせまいので、自動車がすれ違うのは大変だ。" },
  { id: 179, unit: "Unit 2", part: "Unit 2", kanji: "掛かる", kana: "かかる", romaji: "kakaru", hanviet: "Quải", nghia: "Tốn, mất, treo", vidu: "このサラダには何もかかっていないようだ。" },
  { id: 180, unit: "Unit 2", part: "Unit 2", kanji: "掛ける", kana: "かける", romaji: "kakeru", hanviet: "Quải", nghia: "Treo, đeo, đắp", vidu: "料理にしょうゆをかけて食べる。" },
  { id: 181, unit: "Unit 2", part: "Unit 2", kanji: "動く", kana: "うごく", romaji: "ugoku", hanviet: "Động", nghia: "Chuyển động, hoạt động", vidu: "「写真を撮るから動かないでください」" },
  { id: 182, unit: "Unit 2", part: "Unit 2", kanji: "動かす", kana: "うごかす", romaji: "ugokasu", hanviet: "Động", nghia: "Làm cho chuyển động", vidu: "ひどいけがをして、体を動かすこともできない。" },
  { id: 183, unit: "Unit 2", part: "Unit 2", kanji: "離れる", kana: "はなれる", romaji: "hanareru", hanviet: "Ly", nghia: "Rời xa, cách xa", vidu: "「危ないから、ストーブから離れて遊びなさい」" },
  { id: 184, unit: "Unit 2", part: "Unit 2", kanji: "離す", kana: "はなす", romaji: "hanasu", hanviet: "Ly", nghia: "Để xa ra, tách ra", vidu: "テストのときは、机を離して並べる。" },
  { id: 185, unit: "Unit 2", part: "Unit 2", kanji: "ぶつかる", kana: "butsukaru", romaji: "butsukaru", hanviet: "", nghia: "Va chạm, đâm vào", vidu: "道で自転車にぶつかってけがをした。" },
  { id: 186, unit: "Unit 2", part: "Unit 2", kanji: "ぶつける", kana: "butsukeru", romaji: "butsukeru", hanviet: "", nghia: "Đâm vào, húc vào", vidu: "運転していて、車を電柱にぶつけてしまった。" },
  { id: 187, unit: "Unit 2", part: "Unit 2", kanji: "こぼれる", kana: "koboreru", romaji: "koboreru", hanviet: "", nghia: "Bị tràn, bị đổ", vidu: "手がふるえてお茶がこぼれてしまった。" },
  { id: 188, unit: "Unit 2", part: "Unit 2", kanji: "こぼす", kana: "kobosu", romaji: "kobosu", hanviet: "", nghia: "Làm tràn, làm đổ", vidu: "コップを倒して水をこぼしてしまった。" },
  { id: 189, unit: "Unit 2", part: "Unit 2", kanji: "拭く", kana: "ふく", romaji: "fuku", hanviet: "Thức", nghia: "Lau, chùi", vidu: "汗を拭く。" },
  { id: 190, unit: "Unit 2", part: "Unit 2", kanji: "片付く", kana: "かたづく", romaji: "kataduku", hanviet: "Phiến Phó", nghia: "Được dọn dẹp", vidu: "大掃除をして、やっと部屋が片付いた。" },
  { id: 191, unit: "Unit 2", part: "Unit 2", kanji: "片付ける", kana: "かたづける", romaji: "katadukeru", hanviet: "Phiến Phó", nghia: "Dọn dẹp", vidu: "机の上을片付ける。" },
  { id: 192, unit: "Unit 2", part: "Unit 2", kanji: "包む", kana: "つつむ", romaji: "tsutsumu", hanviet: "Bao", nghia: "Gói, bọc", vidu: "プレゼントをきれいな紙で包む。" },
  { id: 193, unit: "Unit 2", part: "Unit 2", kanji: "張る", kana: "はる", romaji: "haru", hanviet: "Trương", nghia: "Dán", vidu: "壁にポスターを張る。" },
  { id: 194, unit: "Unit 2", part: "Unit 2", kanji: "無くなる", kana: "なくなる", romaji: "nakunaru", hanviet: "Vô", nghia: "Bị mất, hết", vidu: "部屋のかぎがなくなってしまった。" },
  { id: 195, unit: "Unit 2", part: "Unit 2", kanji: "無くす", kana: "なくす", romaji: "nakusu", hanviet: "Vô", nghia: "Làm mất", vidu: "パスポートをなくして困っている。" },
  { id: 196, unit: "Unit 2", part: "Unit 2", kanji: "足りる", kana: "たりる", romaji: "tariru", hanviet: "Túc", nghia: "Đầy đủ", vidu: "この収入では生活するのに全然足りない。" },
  { id: 197, unit: "Unit 2", part: "Unit 2", kanji: "残る", kana: "のこる", romaji: "nokoru", hanviet: "Tàn", nghia: "Còn lại, sót lại", vidu: "料理を作りすぎて、たくさん残ってしまった。" },
  { id: 198, unit: "Unit 2", part: "Unit 2", kanji: "残す", kana: "のこす", romaji: "nokosu", hanviet: "Tàn", nghia: "Để lại", vidu: "ごはんを残してしまった。" },
  { id: 199, unit: "Unit 2", part: "Unit 2", kanji: "腐る", kana: "くさる", romaji: "kusaru", hanviet: "Hủ", nghia: "Thối, thiu, hỏng", vidu: "腐ったものを食べて、おなかを壊してしまった。" },
  { id: 200, unit: "Unit 2", part: "Unit 2", kanji: "剥ける", kana: "むける", romaji: "mukeru", hanviet: "Bác", nghia: "Bị lột, bong ra", vidu: "海で日焼けをして、背中の皮がむけた。" },
  { id: 201, unit: "Unit 2", part: "Unit 2", kanji: "剥く", kana: "むく", romaji: "muku", hanviet: "Bác", nghia: "Gọt, lột, bóc", vidu: "果物の皮をむく。" },
  { id: 202, unit: "Unit 2", part: "Unit 2", kanji: "滑る", kana: "すべる", romaji: "suberu", hanviet: "Hoạt", nghia: "Trượt", vidu: "新しいスケート場はきれいで、楽しくすべることができた。" },
  { id: 203, unit: "Unit 2", part: "Unit 2", kanji: "積もる", kana: "つもる", romaji: "tsumoru", hanviet: "Tích", nghia: "Chất đống, tích tụ", vidu: "きのう降った雪が積もっている。" },
  { id: 204, unit: "Unit 2", part: "Unit 2", kanji: "積む", kana: "つむ", romaji: "tsumu", hanviet: "Tích", nghia: "Chất, xếp, tích lũy", vidu: "机の上に本がたくさん積んである。" },
  { id: 205, unit: "Unit 2", part: "Unit 2", kanji: "空く", kana: "あく", romaji: "aku", hanviet: "Không", nghia: "Trống, hở, vắng", vidu: "くつのしたに穴が空いてしまった。" },
  { id: 206, unit: "Unit 2", part: "Unit 2", kanji: "空ける", kana: "あける", romaji: "akeru", hanviet: "Không", nghia: "Làm trống, để cách", vidu: "かべに穴を空ける。" },
  { id: 207, unit: "Unit 2", part: "Unit 2", kanji: "下がる", kana: "さがる", romaji: "sagaru", hanviet: "Hạ", nghia: "Hạ xuống, giảm đi", vidu: "熱が下がる。" },
  { id: 208, unit: "Unit 2", part: "Unit 2", kanji: "下げる", kana: "さげる", romaji: "sageru", hanviet: "Hạ", nghia: "Làm hạ xuống, giảm", vidu: "熱を下げる。" },
  { id: 209, unit: "Unit 2", part: "Unit 2", kanji: "冷える", kana: "ひえる", romaji: "hieru", hanviet: "Lãnh", nghia: "Lạnh đi, nguội đi", vidu: "寒いところに長くいたので、手足が冷えてしまった。" },
  { id: 210, unit: "Unit 2", part: "Unit 2", kanji: "冷やす", kana: "ひやす", romaji: "hiyasu", hanviet: "Lãnh", nghia: "Làm lạnh", vidu: "この果物は冷やして食べたほうがいい。" },
  { id: 211, unit: "Unit 2", part: "Unit 2", kanji: "冷める", kana: "さめる", romaji: "sameru", hanviet: "Lãnh", nghia: "Nguội đi, mất hứng", vidu: "この料理は冷めるとおいしくない。" },
  { id: 212, unit: "Unit 2", part: "Unit 2", kanji: "冷ます", kana: "さます", romaji: "samasu", hanviet: "Lãnh", nghia: "Làm nguội", vidu: "お風呂のお湯が熱くなりすぎた。少し冷ましてから入ろう。" },
  { id: 213, unit: "Unit 2", part: "Unit 2", kanji: "燃える", kana: "もえる", romaji: "moeru", hanviet: "Nhiên", nghia: "Cháy", vidu: "火で紙が燃える。" },
  { id: 214, unit: "Unit 2", part: "Unit 2", kanji: "燃やす", kana: "もやす", romaji: "moyasu", hanviet: "Nhiên", nghia: "Đốt, thiêu", vidu: "火で紙を燃やす。" },
  { id: 215, unit: "Unit 2", part: "Unit 2", kanji: "沸く", kana: "わく", romaji: "waku", hanviet: "Phí", nghia: "Sôi", vidu: "湯が沸く。" },
  { id: 216, unit: "Unit 2", part: "Unit 2", kanji: "沸かす", kana: "わかす", romaji: "wakasu", hanviet: "Phí", nghia: "Đun sôi", vidu: "湯を沸かす。" },
  { id: 217, unit: "Unit 2", part: "Unit 2", kanji: "鳴る", kana: "なる", romaji: "naru", hanviet: "Minh", nghia: "Kêu, reo", vidu: "雷が鳴っている。" },
  { id: 218, unit: "Unit 2", part: "Unit 2", kanji: "鳴らす", kana: "ならす", romaji: "narasu", hanviet: "Minh", nghia: "Làm cho kêu, reo", vidu: "ブザーを鳴らす。" },
  { id: 219, unit: "Unit 2", part: "Unit 2", kanji: "役立つ", kana: "やくだつ", romaji: "yakudatsu", hanviet: "Dịch Lập", nghia: "Có ích", vidu: "インターネットの情報は、勉強や仕事に役立つ。" },
  { id: 220, unit: "Unit 2", part: "Unit 2", kanji: "役立てる", kana: "やくだてる", romaji: "yakudateru", hanviet: "Dịch Lập", nghia: "Đưa vào sử dụng, ứng dụng", vidu: "インターネットの情報を、勉強や仕事に役立てる。" },
  { id: 221, unit: "Unit 2", part: "Unit 2", kanji: "飾り", kana: "かざり", romaji: "kazari", hanviet: "Sức", nghia: "Đồ trang trí", vidu: "クリスマスの飾りを買った。" },
  { id: 222, unit: "Unit 2", part: "Unit 2", kanji: "遊び", kana: "あそび", romaji: "asobi", hanviet: "Du", nghia: "Trò chơi, vui chơi", vidu: "かくれんぼは子どもの遊びだ。" },
  { id: 223, unit: "Unit 2", part: "Unit 2", kanji: "集まり", kana: "あつまり", romaji: "atsumari", hanviet: "Tập", nghia: "Cuộc họp, sự tập trung", vidu: "あした、マンションの住人の集まりがある。" },
  { id: 224, unit: "Unit 2", part: "Unit 2", kanji: "教え", kana: "おしえ", romaji: "oshie", hanviet: "Giáo", nghia: "Lời dạy", vidu: "母の教えを今でも思い出す。" },
  { id: 225, unit: "Unit 2", part: "Unit 2", kanji: "踊り", kana: "おどり", romaji: "odori", hanviet: "Dũng", nghia: "Điệu nhảy", vidu: "留学生が各国の踊りを踊った。" },
  { id: 226, unit: "Unit 2", part: "Unit 2", kanji: "思い", kana: "おもい", romaji: "omoi", hanviet: "Tư", nghia: "Suy nghĩ, cảm xúc", vidu: "あの人に私の思いが届いた。" },
  { id: 227, unit: "Unit 2", part: "Unit 2", kanji: "考え", kana: "かんがえ", romaji: "kangae", hanviet: "Khảo", nghia: "Suy nghĩ, ý tưởng", vidu: "私にいい考えがある。" },
  { id: 228, unit: "Unit 2", part: "Unit 2", kanji: "片づけ", kana: "かたづけ", romaji: "kataduke", hanviet: "Phiến Phó", nghia: "Việc dọn dẹp", vidu: "私は片づけが苦手だ。" },
  { id: 229, unit: "Unit 2", part: "Unit 2", kanji: "手伝い", kana: "てつだい", romaji: "tetsudai", hanviet: "Thủ Truyền", nghia: "Sự giúp đỡ", vidu: "引っ越しの手伝いをする。" },
  { id: 230, unit: "Unit 2", part: "Unit 2", kanji: "働き", kana: "はたらき", romaji: "hataraki", hanviet: "Động", nghia: "Hoạt động, chức năng", vidu: "血液の働きの一つは、体に栄養を運ぶことだ。" },
  { id: 231, unit: "Unit 2", part: "Unit 2", kanji: "決まり", kana: "きまり", romaji: "kimari", hanviet: "Quyết", nghia: "Quy định, quy tắc", vidu: "学校で新しい決まりが作られた。" },
  { id: 232, unit: "Unit 2", part: "Unit 2", kanji: "騒ぎ", kana: "さわぎ", romaji: "sawagi", hanviet: "Tào", nghia: "Sự ồn ào, náo loạn", vidu: "きのう、駅前で騒ぎがあった。" },
  { id: 233, unit: "Unit 2", part: "Unit 2", kanji: "知らせ", kana: "しらせ", romaji: "shirase", hanviet: "Tri", nghia: "Thông báo, tin tức", vidu: "父が入院したという知らせがあった。" },
  { id: 234, unit: "Unit 2", part: "Unit 2", kanji: "頼み", kana: "たのみ", romaji: "tanomi", hanviet: "Lại", nghia: "Lời nhờ vả, yêu cầu", vidu: "「あなたに頼みがあるんです」" },
  { id: 235, unit: "Unit 2", part: "Unit 2", kanji: "疲れ", kana: "つかれ", romaji: "tsukare", hanviet: "Bì", nghia: "Sự mệt mỏi", vidu: "仕事で疲れがたまっている。" },
  { id: 236, unit: "Unit 2", part: "Unit 2", kanji: "違い", kana: "違い", romaji: "chigai", hanviet: "Vi", nghia: "Sự khác biệt", vidu: "この二つの違いがわからない。" },
  { id: 237, unit: "Unit 2", part: "Unit 2", kanji: "始め", kana: "はじめ", romaji: "hajime", hanviet: "Thủy", nghia: "Lúc bắt đầu", vidu: "本を始めから終わりまで全部読んだ。" },
  { id: 238, unit: "Unit 2", part: "Unit 2", kanji: "続き", kana: "つづき", romaji: "tsuduki", hanviet: "Tục", nghia: "Sự tiếp tục, phần tiếp theo", vidu: "早く本の続きが読いたい。" },
  { id: 239, unit: "Unit 2", part: "Unit 2", kanji: "暮れ", kana: "くれ", romaji: "kure", hanviet: "Mộ", nghia: "Cuối (năm), chiều tối", vidu: "年の暮れは忙しい。" },
  { id: 240, unit: "Unit 2", part: "Unit 2", kanji: "行き", kana: "いき", romaji: "iki", hanviet: "Hành", nghia: "Chiều đi, hướng đi", vidu: "旅行は、行きは新幹線、帰りは飛行機だった。" },
  { id: 241, unit: "Unit 2", part: "Unit 2", kanji: "帰り", kana: "かえり", romaji: "kaeri", hanviet: "Quy", nghia: "Chiều về", vidu: "帰りにコンビニに寄る。" },
  { id: 242, unit: "Unit 2", part: "Unit 2", kanji: "急ぎ", kana: "いそぎ", romaji: "isogi", hanviet: "Cấp", nghia: "Việc gấp, sự vội vàng", vidu: "急ぎの仕事が入った。" },
  { id: 243, unit: "Unit 2", part: "Unit 2", kanji: "遅れ", kana: "おくれ", romaji: "okure", hanviet: "Trì", nghia: "Sự chậm trễ, muộn", vidu: "電車に3分の遅れが出た。" },
  { id: 244, unit: "Unit 2", part: "Unit 2", kanji: "貸し", kana: "かし", romaji: "kashi", hanviet: "Thải", nghia: "Việc cho vay", vidu: "あの人には10万円の貸しがある。" },
  { id: 245, unit: "Unit 2", part: "Unit 2", kanji: "借り", kana: "かり", romaji: "kari", hanviet: "Tá", nghia: "Việc vay mượn", vidu: "借りは返さなければならない。" },
  { id: 246, unit: "Unit 2", part: "Unit 2", kanji: "勝ち", kana: "かち", romaji: "kachi", hanviet: "Thắng", nghia: "Chiến thắng", vidu: "きょうの試合はAチームの勝ちだった。" },
  { id: 247, unit: "Unit 2", part: "Unit 2", kanji: "負け", kana: "まけ", romaji: "make", hanviet: "Phụ", nghia: "Trận thua, thất bại", vidu: "負けが続いて、いやになった。" },
  { id: 248, unit: "Unit 2", part: "Unit 2", kanji: "迎え", kana: "むかえ", romaji: "mukae", hanviet: "Nghênh", nghia: "Việc đón", vidu: "迎えの車がなかなか来ない。" },
  { id: 249, unit: "Unit 2", part: "Unit 2", kanji: "始まり", kana: "はじまり", romaji: "hajimari", hanviet: "Thủy", nghia: "Sự bắt đầu", vidu: "映画の始まりに間に合わなかった。" },
  { id: 250, unit: "Unit 2", part: "Unit 2", kanji: "終わり", kana: "おわり", romaji: "owari", hanviet: "Chung", nghia: "Sự kết thúc", vidu: "夏休みはもうすぐ終わりだ。" },
  { id: 251, unit: "Unit 2", part: "Unit 2", kanji: "戻り", kana: "もどり", romaji: "modori", hanviet: "Lệ", nghia: "Việc quay lại", vidu: "「きょうの戻りは3時ごろになります」" },
  { id: 252, unit: "Unit 2", part: "Unit 2", kanji: "別れ", kana: "わかれ", romaji: "wakare", hanviet: "Biệt", nghia: "Sự chia tay", vidu: "日本では3月は別れの季節だ。" },
  { id: 253, unit: "Unit 2", part: "Unit 2", kanji: "喜び", kana: "よろこび", romaji: "yorokobi", hanviet: "Hỷ", nghia: "Niềm vui", vidu: "優勝できて、喜びでいっぱいだ。" },
  { id: 254, unit: "Unit 2", part: "Unit 2", kanji: "楽しみ", kana: "たのしみ", romaji: "tanoshimi", hanviet: "Lạc", nghia: "Niềm vui, sự mong đợi", vidu: "来週のパーティーが楽しみだ。" },
  { id: 255, unit: "Unit 2", part: "Unit 2", kanji: "笑い", kana: "わらい", romaji: "warai", hanviet: "Tiếu", nghia: "Tiếng cười", vidu: "歌手の冗談で会場に笑いが起きた。" },
  { id: 256, unit: "Unit 2", part: "Unit 2", kanji: "驚き", kana: "おどろき", romaji: "odoroki", hanviet: "Kinh", nghia: "Sự ngạc nhiên", vidu: "この大きな家がたったの100万円とは驚きだ。" },
  { id: 257, unit: "Unit 2", part: "Unit 2", kanji: "怒り", kana: "いかり", romaji: "ikari", hanviet: "Nộ", nghia: "Cơn giận", vidu: "殺人のニュースに怒りを感じた。" },
  { id: 258, unit: "Unit 2", part: "Unit 2", kanji: "悲しみ", kana: "かなしみ", romaji: "kanashimi", hanviet: "Bi", nghia: "Sự đau buồn", vidu: "愛犬を亡くした悲しみが消えない。" },
  { id: 259, unit: "Unit 3", part: "Unit 3", kanji: "幸せな", kana: "しあわせな", romaji: "shiawasena", hanviet: "Hạnh", nghia: "Hạnh phúc", vidu: "幸せな人生。" },
  { id: 260, unit: "Unit 3", part: "Unit 3", kanji: "得意な", kana: "とくいな", romaji: "tokuina", hanviet: "Đắc Ý", nghia: "Giỏi, đắc ý", vidu: "彼女はギターが得意だ。" },
  { id: 261, unit: "Unit 3", part: "Unit 3", kanji: "苦手な", kana: "いがてな", romaji: "nigatena", hanviet: "Khổ Thủ", nghia: "Kém, yếu", vidu: "彼女はギターが苦手だ。" },
  { id: 262, unit: "Unit 3", part: "Unit 3", kanji: "熱心な", kana: "ねっしんな", romaji: "nesshinna", hanviet: "Nhiệt Tâm", nghia: "Nhiệt tình", vidu: "熱心な仕事ぶりが認められて昇進した。" },
  { id: 263, unit: "Unit 3", part: "Unit 3", kanji: "夢中な", kana: "むちゅうな", romaji: "muchuuna", hanviet: "Mộng Trung", nghia: "Say mê", vidu: "子どものころ、SF漫画に夢中になった。" },
  { id: 264, unit: "Unit 3", part: "Unit 3", kanji: "退屈な", kana: "たいくつな", romaji: "taikutsuna", hanviet: "Thoái Khuất", nghia: "Buồn chán", vidu: "ほかの観客は笑いながら見ていたが、私には退屈な映画だった。" },
  { id: 265, unit: "Unit 3", part: "Unit 3", kanji: "健康な", kana: "けんこうな", romaji: "kenkouna", hanviet: "Kiện Khang", nghia: "Khỏe mạnh", vidu: "心も体も健康な子どもを育てたい。" },
  { id: 266, unit: "Unit 3", part: "Unit 3", kanji: "苦しい", kana: "くるしい", romaji: "kurushii", hanviet: "Khổ", nghia: "Khổ cực, đau đớn", vidu: "息が苦しい。" },
  { id: 267, unit: "Unit 3", part: "Unit 3", kanji: "平気な", kana: "へいきな", romaji: "heikina", hanviet: "Bình Khí", nghia: "Bình thản", vidu: "彼女は、どんなに悪口を言われても平気な顔をしている。" },
  { id: 268, unit: "Unit 3", part: "Unit 3", kanji: "悔しい", kana: "くやしい", romaji: "kuyashii", hanviet: "Hối", nghia: "Đáng tiếc, cay cú", vidu: "たった1点差で試合に負けて悔しい思いをした。" },
  { id: 269, unit: "Unit 3", part: "Unit 3", kanji: "羨ましい", kana: "うらやましい", romaji: "urayamashii", hanviet: "Tiện", nghia: "Ghen tị, thèm muốn", vidu: "才能の豊かな人がうらやましい。" },
  { id: 270, unit: "Unit 3", part: "Unit 3", kanji: "痒い", kana: "かゆい", romaji: "kayui", hanviet: "Dương", nghia: "Ngứa", vidu: "蚊に刺されて首がかゆい。" },
  { id: 271, unit: "Unit 3", part: "Unit 3", kanji: "おとなしい", kana: "おとなしい", romaji: "otonashii", hanviet: "", nghia: "Hiền lành, trầm lặng", vidu: "彼はおとなしい人だ。" },
  { id: 272, unit: "Unit 3", part: "Unit 3", kanji: "我慢強い", kana: "がまんづよい", romaji: "gamanzuyoi", hanviet: "Ngã Mạn Cường", nghia: "Kiên trì, nhẫn nại", vidu: "我慢強い性格。" },
  { id: 273, unit: "Unit 3", part: "Unit 3", kanji: "正直な", kana: "しょうじきな", romaji: "shoujikina", hanviet: "Chính Trực", nghia: "Thành thật", vidu: "彼は正直な人だから、うそをつくことができない。" },
  { id: 274, unit: "Unit 3", part: "Unit 3", kanji: "けちな", kana: "けちな", romaji: "kechina", hanviet: "", nghia: "Keo kiệt", vidu: "あの人はとてもけちだ。" },
  { id: 275, unit: "Unit 3", part: "Unit 3", kanji: "わがままな", kana: "わがままな", romaji: "wagamamana", hanviet: "", nghia: "Ích kỷ, bướng bỉnh", vidu: "わがままな人。" },
  { id: 276, unit: "Unit 3", part: "Unit 3", kanji: "積極的な", kana: "せっきょくてきな", romaji: "sekkyokutekina", hanviet: "Tích Cực Đích", nghia: "Tích cực", vidu: "積極的な人。" },
  { id: 277, unit: "Unit 3", part: "Unit 3", kanji: "消極的な", kana: "しょうきょくてきな", romaji: "shoukyokutekina", hanviet: "Tiêu Cực Đích", nghia: "Tiêu cực", vidu: "消極的な人。" },
  { id: 278, unit: "Unit 3", part: "Unit 3", kanji: "満足な", kana: "まんぞくな", romaji: "manzokuna", hanviet: "Mãn Túc", nghia: "Thỏa mãn, hài lòng", vidu: "アルバイトだけでは満足な収入は得られない。" },
  { id: 279, unit: "Unit 3", part: "Unit 3", kanji: "不満な", kana: "ふまんな", romaji: "fumanna", hanviet: "Bất Mãn", nghia: "Bất mãn, không hài lòng", vidu: "この仕事に不満な点はない。" },
  { id: 280, unit: "Unit 3", part: "Unit 3", kanji: "不安な", kana: "ふあんな", romaji: "fuanna", hanviet: "Bất An", nghia: "Bất an, lo lắng", vidu: "最近、体の調子がよくない。悪い病気ではないかと不安だ。" },
  { id: 281, unit: "Unit 3", part: "Unit 3", kanji: "大変な", kana: "たいへんな", romaji: "taihenna", hanviet: "Đại Biến", nghia: "Vất vả, vất vả cực nhọc", vidu: "子育て中のお母さんは大変だ。" },
  { id: 282, unit: "Unit 3", part: "Unit 3", kanji: "無理な", kana: "むりな", romaji: "murina", hanviet: "Vô Lý", nghia: "Vô lý, quá sức", vidu: "たった100万円で家を建てるなんて無理な話だ。" },
  { id: 283, unit: "Unit 3", part: "Unit 3", kanji: "不注意な", kana: "ふちゅういな", romaji: "fuchuuyina", hanviet: "Bất Chú Ý", nghia: "Không chú ý, bất cẩn", vidu: "不注意な人。" },
  { id: 284, unit: "Unit 3", part: "Unit 3", kanji: "楽な", kana: "らくな", romaji: "rakuna", hanviet: "Lạc", nghia: "Thoải mái, nhàn nhã", vidu: "もう少し楽な暮らしがしたい。" },
  { id: 285, unit: "Unit 3", part: "Unit 3", kanji: "面倒な", kana: "めんどうな", romaji: "mendouna", hanviet: "Diện Đảo", nghia: "Phiền hà, rắc rối", vidu: "ご入会にめんどうな手続きはいりません。" },
  { id: 286, unit: "Unit 3", part: "Unit 3", kanji: "失礼な", kana: "しつれいな", romaji: "shitsureina", hanviet: "Thất Lễ", nghia: "Thất lễ, vô phép", vidu: "あいさつしても返事もしない。なんて失礼な人だろう。" },
  { id: 287, unit: "Unit 3", part: "Unit 3", kanji: "当然な", kana: "とうぜんな", romaji: "touzenna", hanviet: "Đương Nhiên", nghia: "Đương nhiên, tất nhiên", vidu: "お金を借りたら、返すのが当然だ。" },
  { id: 288, unit: "Unit 3", part: "Unit 3", kanji: "意外な", kana: "いがいな", romaji: "igaina", hanviet: "Ý Ngoại", nghia: "Ngoài dự tính, bất ngờ", vidu: "事故を調査するうちに意外な事実がわかった。" },
  { id: 289, unit: "Unit 3", part: "Unit 3", kanji: "結構な", kana: "けっこうな", romaji: "kekkouna", hanviet: "Kết Cấu", nghia: "Tốt, ổn, tuyệt", vidu: "お味はいかがですか。大変結構です。" },
  { id: 290, unit: "Unit 3", part: "Unit 3", kanji: "派手な", kana: "はでな", romaji: "hadena", hanviet: "Phái Thủ", nghia: "Lòe loẹt, sặc sỡ", vidu: "はでな性格。" },
  { id: 291, unit: "Unit 3", part: "Unit 3", kanji: "地味な", kana: "じみな", romaji: "jimina", hanviet: "Địa Vị", nghia: "Giản dị, đơn sơ", vidu: "じみな性格。" },
  { id: 292, unit: "Unit 3", part: "Unit 3", kanji: "おしゃれな", kana: "おしゃれな", romaji: "osharena", hanviet: "", nghia: "Sang trọng, thời thượng", vidu: "彼女はとてもおしゃれだ。" },
  { id: 293, unit: "Unit 3", part: "Unit 3", kanji: "変な", kana: "へんな", romaji: "henna", hanviet: "Biến", nghia: "Lạ, kỳ lạ", vidu: "変なメールが届いたのですぐに消した。" },
  { id: 294, unit: "Unit 3", part: "Unit 3", kanji: "不思議な", kana: "ふしぎな", romaji: "fushigina", hanviet: "Bất Tư Nghị", nghia: "Kỳ lạ, huyền bí", vidu: "この village には不思議な話が伝わっている。" },
  { id: 295, unit: "Unit 3", part: "Unit 3", kanji: "ましな", kana: "ましな", romaji: "mashina", hanviet: "", nghia: "Đỡ hơn, tốt hơn", vidu: "せきがひどかったが、うがいをしたら前よりましになった。" },
  { id: 296, unit: "Unit 3", part: "Unit 3", kanji: "むだな", kana: "むだな", romaji: "mudana", hanviet: "", nghia: "Lãng phí, vô ích", vidu: "落ちるとわかっているのに試験を受けるのは、むだなことだ。" },
  { id: 297, unit: "Unit 3", part: "Unit 3", kanji: "自由な", kana: "じゆうな", romaji: "jiyuuna", hanviet: "Tự Do", nghia: "Tự do", vidu: "赤ちゃんがいるので、自由な時間がほとんどない。" },
  { id: 298, unit: "Unit 3", part: "Unit 3", kanji: "不自由な", kana: "ふじゆうな", romaji: "fujiyuuna", hanviet: "Bất Tự Do", nghia: "Tàn tật, bất tiện", vidu: "目が不自由な人。" }
];